In [103]:
import geopandas as gpd
import pandas as pd
import datetime as dt
pd.set_option('display.max_columns', None)
import numpy as np

In [104]:
trees = gpd.read_file("/Users/prince/philly-tree-mapper/data/processed/philly_trees_located.geojson")
phenos = gpd.read_file("../data/processed/philly_species_pheno.geojson")

In [105]:
non_specific_pheno = phenos.loc[phenos["Species"] == "species"]

In [23]:
non_specific_pheno

,objectid,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Active Growth Period,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL,geometry
114,16962,Picea species - norway spruce,picea species,norway spruce,Picea,species,PIAB,Spring and Summer,No,Yellow,No,Dark Green,Dense,Dense,Brown,No,Yes,Mid Spring,Medium,Summer,Fall,No,picea species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-74.99181 40.05301)
191,10,Amelanchier species - other serviceberry,amelanchier species,other serviceberry,Amelanchier,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,amelanchier species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.20996 39.98388)
193,40,Prunus species - other cherry,prunus species,other cherry,Prunus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,prunus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.1213 40.02181)
200,65,Malus species - other crabapple,malus species,other crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21236 39.98367)
202,84,Magnolia species - other magnolia,magnolia species,other magnolia,Magnolia,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,magnolia species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.20916 39.94819)
203,124,Crataegus species - other hawthorn,crataegus species,other hawthorn,Crataegus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,crataegus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.20933 39.94716)
204,156,Aesculus species - other buckeye,aesculus species,other buckeye,Aesculus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aesculus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21076 39.94782)
209,261,Ulmus species - other elm,ulmus species,other elm,Ulmus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ulmus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21045 39.94855)
212,367,Cornus species - other dogwood,cornus species,other dogwood,Cornus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cornus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.22201 39.94823)
222,705,Taxus species - yew,taxus species,yew,Taxus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taxus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.20904 39.98306)
223,772,Salix species - other willow,salix species,other willow,Salix,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,salix species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21118 39.98364)
224,832,Pinus species - other pine,pinus species,other pine,Pinus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pinus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21423 39.98326)
227,883,Carya species - other hickory,carya species,other hickory,Carya,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carya species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21394 39.98223)
230,1268,Acer species - other maple,acer species,other maple,Acer,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,acer species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.17707 40.05114)
234,1796,Quercus species - other oak,quercus species,other oak,Quercus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,quercus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.16901 40.02086)
235,1831,Abies species - other fir,abies species,other fir,Abies,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,abies species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.18114 40.02538)
240,4485,Fraxinus species - other ash,fraxinus species,other ash,Fraxinus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fraxinus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.05936 40.08777)
242,4620,Tilia species - other linden,tilia species,other linden,Tilia,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tilia species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.1712 39.91524)
244,5034,Picea species - other spruce,picea species,other spruce,Picea,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,picea species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.24744 39.96538)
246,7017,Ilex species - other holly,ilex species,other holly,Ilex,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ilex species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.17152 39.94926)
250,9477,Poplar species - other poplar,poplar species,other poplar,Poplar,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,poplar species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-74.99859 40.06203)
251,10542,Fagus species - other beech,fagus species,other beech,Fagus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fagus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.0657 40.02434)
255,11496,Castanea species - other chestnut,castanea species,other chestnut,Castanea,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,castanea species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.18779 39.99251)
257,12024,Stewartia species - other stewartia,stewartia species,other stewartia,Stewartia,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,stewartia species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.17973 39.966)
262,18578,Cupressus species - other cypress,cupressus species,other cypress,Cupressus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cupressus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.1686 39.96176)
266,31517,Betula species - other birch,betula species,other birch,Betula,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,betula species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.25763 39.97739)
269,37268,Malus species - harvest gold crabapple,malus species,harvest gold crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21556 40.04068)
275,38713,Malus species - spring snow crabapple,malus species,spring snow crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.17545 39.96941)
277,40242,Alnus species – other alder,alnus species,other alder,Alnus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,alnus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.12406 39.98135)
280,46170,Malus species - snowdrift crabapple,malus species,snowdrift crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.16428 39.93148)
282,48559,Sorbus species - other mountain ash,sorbus species,other mountain ash,Sorbus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sorbus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.15008 39.93725)
288,52961,Malus species - pink spires crabapple,malus species,pink spires crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.16917 39.94613)
289,69306,Malus species - sugar tyme crabapple,malus species,sugar tyme crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.15918 39.96229)
290,78656,Rosa species - other rose,rosa species,other rose,Rosa,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rosa species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.14111 39.99438)
292,148593,Malus species - indian summer crabapple,malus species,indian summer crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21815 39.94158)

In [47]:
phenos.loc[phenos["Genus"] == "Cornus"]

,objectid,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Active Growth Period,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL,geometry
59,37602,Cornus florida - flowering dogwood,cornus florida,flowering dogwood,Cornus,florida,COFL2,Spring and Summer,Yes,White,Yes,Green,Porous,Porous,Red,Yes,No,Early Spring,Medium,Spring,Fall,No,cornus florida,April to May,White (bracts),Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...,POINT (-75.24698 39.96317)
60,59585,Cornus mas - corneliancherry dogwood,cornus mas,corneliancherry dogwood,Cornus,mas,COMA21,Spring and Summer,Yes,Yellow,Yes,Green,Dense,Moderate,Red,Yes,No,Mid Spring,High,Spring,Summer,Yes,cornus mas,March,Yellow,Showy,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...,POINT (-75.1613 39.94162)
190,9,Cornus kousa - kousa dogwood,cornus kousa,kousa dogwood,Cornus,kousa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cornus kousa,May to June,White to pinkish (bracts),Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...,POINT (-75.21003 39.98398)
212,367,Cornus species - other dogwood,cornus species,other dogwood,Cornus,species,NaN,Spring and Summer,Yes,White to Yellow,Yes,Green,Porous to Dense,Porous to Moderate,Red,Yes,No,Early Spring to Mid Spring,Medium to High,Spring,Summer to Fall,No,cornus species,May to June,White (bracts) to Yellow to White to Pinkish,Showy,Good Fall,aggregated,NaN,POINT (-75.22201 39.94823)
274,38626,Cornus x rutban - aurora dogwood,cornus rutban,aurora dogwood,Cornus,rutban,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cornus rutban,N/a,N/a,N/a,N/a,no results container,NaN,POINT (-75.15894 39.95651)

In [46]:
# Adding phenology information to non generalized tree species
picea_row = {
    'tree_name': 'Picea species - other spruce',
    'scientific_name': 'picea species',
    'common_name': 'other spruce',
    'Genus': 'Picea',
    'Species': 'species',
    'plant_code': np.nan,
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': 'No',
    'Morphology/Physiology | Flower Color': 'Yellow',
    'Morphology/Physiology | Flower Conspicuous': 'No',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Dense',
    'Morphology/Physiology | Foliage Porosity Winter': 'Dense',
    'Morphology/Physiology | Fruit/Seed Color': 'Brown',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'No',
    'Morphology/Physiology | Leaf Retention': 'Yes',
    'Reproduction | Bloom Period': 'Late Spring',
    'Reproduction | Fruit/Seed Abundance': 'High',
    'Reproduction | Fruit/Seed Period Begin': 'Summer',
    'Reproduction | Fruit/Seed Period End': 'Fall',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'picea species',
    'Bloom Time': 'Non-flowering',
    'Bloom Description': 'Non-flowering',
    'Flower': 'N/a',
    'Leaf': 'Evergreen',
    'Status': 'aggregated',
}
phenos.loc[phenos.index[244], list(picea_row.keys())] = list(picea_row.values())

amelanchier_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': 'Yes',
    'Morphology/Physiology | Flower Color': 'White',
    'Morphology/Physiology | Flower Conspicuous': 'Yes',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Moderate',
    'Morphology/Physiology | Foliage Porosity Winter': 'Porous',
    'Morphology/Physiology | Fruit/Seed Color': 'Red and Purple',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'Yes',
    'Morphology/Physiology | Leaf Retention': 'No',
    'Reproduction | Bloom Period': 'Spring',
    'Reproduction | Fruit/Seed Abundance': 'Medium',
    'Reproduction | Fruit/Seed Period Begin': 'Spring',
    'Reproduction | Fruit/Seed Period End': 'Summer',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'amelanchier species',
    'Bloom Time': 'March to April',
    'Bloom Description': 'White',
    'Flower': 'Showy, Fragrant',
    'Leaf': 'Good Fall',
    'Status': 'aggregated',
}
phenos.loc[phenos.index[191], list(amelanchier_row.keys())] = list(amelanchier_row.values())

prunus_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': np.nan,
    'Morphology/Physiology | Flower Color': 'Pink to White',
    'Morphology/Physiology | Flower Conspicuous': 'Yes',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Moderate',
    'Morphology/Physiology | Foliage Porosity Winter': 'Porous',
    'Morphology/Physiology | Fruit/Seed Color': 'Red to Black',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'Yes',
    'Morphology/Physiology | Leaf Retention': 'No',
    'Reproduction | Bloom Period': 'Spring',
    'Reproduction | Fruit/Seed Abundance': 'High',
    'Reproduction | Fruit/Seed Period Begin': 'Summer',
    'Reproduction | Fruit/Seed Period End': 'Summer',
    'Suitability/Use | Palatable Human': 'Yes',
    'Scientific Name': 'prunus species',
    'Bloom Time': 'February to May',
    'Bloom Description': 'White',
    'Flower': 'Showy, Fragrant',
    'Leaf': 'Good Fall',
    'Status': 'aggregated',
}
phenos.loc[phenos.index[193], list(prunus_row.keys())] = list(prunus_row.values())

magnolia_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': np.nan,
    'Morphology/Physiology | Flower Color': 'Yellow to White',
    'Morphology/Physiology | Flower Conspicuous': 'Yes',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Dense',
    'Morphology/Physiology | Foliage Porosity Winter': 'Moderate',
    'Morphology/Physiology | Fruit/Seed Color': np.nan,
    'Morphology/Physiology | Fruit/Seed Conspicuous': np.nan,
    'Morphology/Physiology | Leaf Retention': np.nan,
    'Reproduction | Bloom Period': 'Spring to Winter',
    'Reproduction | Fruit/Seed Abundance': 'Medium',
    'Reproduction | Fruit/Seed Period Begin': 'Spring',
    'Reproduction | Fruit/Seed Period End': 'Winter',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'magnolia species',
    'Bloom Time': 'April to June',
    'Bloom Description': 'Yellow to White',
    'Flower': 'Showy, Fragrant',
    'Leaf': np.nan,
    'Status': 'aggregated',
}
phenos.loc[phenos.index[202], list(magnolia_row.keys())] = list(magnolia_row.values())
crataegus_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': 'Yes',
    'Morphology/Physiology | Flower Color': 'Purple to White',
    'Morphology/Physiology | Flower Conspicuous': 'Yes',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Dense',
    'Morphology/Physiology | Foliage Porosity Winter': 'Moderate',
    'Morphology/Physiology | Fruit/Seed Color': 'Red',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'Yes',
    'Morphology/Physiology | Leaf Retention': 'No',
    'Reproduction | Bloom Period': 'Spring',
    'Reproduction | Fruit/Seed Abundance': 'Medium',
    'Reproduction | Fruit/Seed Period Begin': 'Spring',
    'Reproduction | Fruit/Seed Period End': 'Fall',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'crataegus species',
    'Bloom Time': 'May to June',
    'Bloom Description': 'White',
    'Flower': 'Showy, Fragrant',
    'Leaf': 'Good Fall',
    'Status': 'aggregated',
}
phenos.loc[phenos.index[203], list(crataegus_row.keys())] = list(crataegus_row.values())
aesculus_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': 'Yes to No',
    'Morphology/Physiology | Flower Color': 'Yellow to Green to Red',
    'Morphology/Physiology | Flower Conspicuous': 'Yes',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Dense',
    'Morphology/Physiology | Foliage Porosity Winter': 'Porous',
    'Morphology/Physiology | Fruit/Seed Color': 'Brown',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'Yes',
    'Morphology/Physiology | Leaf Retention': 'No',
    'Reproduction | Bloom Period': 'Mid Spring to Late Spring',
    'Reproduction | Fruit/Seed Abundance': 'Medium',
    'Reproduction | Fruit/Seed Period Begin': 'Spring to Summer',
    'Reproduction | Fruit/Seed Period End': 'Fall',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'aesculus species',
    'Bloom Time': 'April to May',
    'Bloom Description': 'Yellow to Red',
    'Flower': 'Showy',
    'Leaf': np.nan,
    'Status': 'aggregated',
}
phenos.loc[phenos.index[204], list(aesculus_row.keys())] = list(aesculus_row.values())
ulmus_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': 'Yes to No',
    'Morphology/Physiology | Flower Color': 'Yellow to Green',
    'Morphology/Physiology | Flower Conspicuous': 'No',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Dense',
    'Morphology/Physiology | Foliage Porosity Winter': 'Porous',
    'Morphology/Physiology | Fruit/Seed Color': 'Brown',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'No',
    'Morphology/Physiology | Leaf Retention': 'No',
    'Reproduction | Bloom Period': 'Early Spring to Late Summer',
    'Reproduction | Fruit/Seed Abundance': 'Medium to High',
    'Reproduction | Fruit/Seed Period Begin': 'Spring',
    'Reproduction | Fruit/Seed Period End': 'Spring',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'ulmus species',
    'Bloom Time': np.nan,
    'Bloom Description': 'Reddish green',
    'Flower': 'Insignificant',
    'Leaf': np.nan,
    'Status': 'aggregated',
}


phenos.loc[phenos.index[209], list(ulmus_row.keys())] = list(ulmus_row.values())
cornus_row = {
    'Morphology/Physiology | Active Growth Period': 'Spring and Summer',
    'Morphology/Physiology | Fall Conspicuous': 'Yes',
    'Morphology/Physiology | Flower Color': 'White to Yellow',
    'Morphology/Physiology | Flower Conspicuous': 'Yes',
    'Morphology/Physiology | Foliage Color': 'Green',
    'Morphology/Physiology | Foliage Porosity Summer': 'Porous to Dense',
    'Morphology/Physiology | Foliage Porosity Winter': 'Porous to Moderate',
    'Morphology/Physiology | Fruit/Seed Color': 'Red',
    'Morphology/Physiology | Fruit/Seed Conspicuous': 'Yes',
    'Morphology/Physiology | Leaf Retention': 'No',
    'Reproduction | Bloom Period': 'Early Spring to Mid Spring',
    'Reproduction | Fruit/Seed Abundance': 'Medium to High',
    'Reproduction | Fruit/Seed Period Begin': 'Spring',
    'Reproduction | Fruit/Seed Period End': 'Summer to Fall',
    'Suitability/Use | Palatable Human': 'No',
    'Scientific Name': 'cornus species',
    'Bloom Time': 'May to June',
    'Bloom Description': 'White (bracts) to Yellow to White to Pinkish',
    'Flower': 'Showy',
    'Leaf': 'Good Fall',
    'Status': 'aggregated',
}

# Replace IDX with the target row index
phenos.loc[phenos.index[212], list(cornus_row.keys())] = list(cornus_row.values())

Skipping malus. Dont know enough about them to make a generalization for 3k trees. Return later?
Stopped at Taxus. Testing writing a df function

In [106]:
non_specifc_genus_list = list(non_specific_pheno["Genus"])
non_specifc_genus_list = [genus for genus in non_specifc_genus_list if genus != "Malus"]
unique_non_specifc_genus_list= list(dict.fromkeys(non_specifc_genus_list))

In [107]:
def aggregate_values(species: str):
    """Parse through trees that were matched with USDA or MOBOT data and apply them to trees that philly observers only got genus for"""
    columns = [
        'Morphology/Physiology | Active Growth Period',
        'Morphology/Physiology | Fall Conspicuous',
        'Morphology/Physiology | Flower Color',
        'Morphology/Physiology | Flower Conspicuous',
        'Morphology/Physiology | Foliage Color',
        'Morphology/Physiology | Foliage Porosity Summer',
        'Morphology/Physiology | Foliage Porosity Winter',
        'Morphology/Physiology | Fruit/Seed Color',
        'Morphology/Physiology | Fruit/Seed Conspicuous',
        'Morphology/Physiology | Leaf Retention',
        'Reproduction | Bloom Period',
        'Reproduction | Fruit/Seed Abundance',
        'Reproduction | Fruit/Seed Period Begin',
        'Reproduction | Fruit/Seed Period End',
        'Suitability/Use | Palatable Human',
        'Bloom Time', 'Bloom Description',
        'Flower', 'Leaf',
    ]

    df = phenos.loc[phenos["Genus"] == species].reset_index(drop=True)
    idx = phenos.index[phenos["scientific_name"] == f"{species.lower()} species"].to_list()
    if not idx:
        print(f"No aggregate row for '{species.lower()} species'")
        return

    for col in columns:
        if phenos[col].dtype != object:
            phenos[col] = phenos[col].astype(object)

        values = []
        for val in df[col]:
            if pd.isna(val):
                continue
            if val in values:
                continue
            values.append(val)

        phenos.at[idx[0], col] = values
        phenos.at[idx[0], "Status"] = "aggregated"

In [120]:
phenos.loc[phenos["Genus"] == "Picea"]

,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Active Growth Period,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status
114,Picea species - norway spruce,picea species,norway spruce,Picea,species,PIAB,"[Spring and Summer, Summer]",[No],[Yellow],[No],"[Dark Green, Green]",[Dense],[Dense],[Brown],[No],[Yes],"[Mid Spring, Late Spring]","[Medium, Low, High]",[Summer],"[Fall, Summer]",[No],picea species,"[N/a, Non-flowering]","[N/a, Non-flowering]",[N/a],"[N/a, Evergreen, Colorful, Evergreen]",aggregated
115,Picea glauca - white spruce,picea glauca,white spruce,Picea,glauca,PIGL,Summer,No,Yellow,No,Green,Dense,Dense,Brown,No,Yes,Late Spring,Low,Summer,Summer,No,picea glauca,Non-flowering,Non-flowering,N/a,Evergreen,matched
116,Picea mariana - black spruce,picea mariana,black spruce,Picea,mariana,PIMA,Summer,No,Yellow,No,Green,Dense,Dense,Brown,No,Yes,Late Spring,Medium,Summer,Summer,No,picea mariana,Non-flowering,Non-flowering,N/a,"Colorful, Evergreen",single result
118,Picea pungens - colorado spruce,picea pungens,colorado spruce,Picea,pungens,PIPU,Spring and Summer,No,Yellow,No,Green,Dense,Dense,Brown,No,Yes,Late Spring,High,Summer,Fall,No,picea pungens,Non-flowering,Non-flowering,N/a,Evergreen,matched
244,Picea species - other spruce,picea species,other spruce,Picea,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,picea species,N/a,N/a,N/a,N/a,no exact match

In [84]:
aggregate_values("Pinus")

In [116]:
phenos.loc[phenos["Genus"] == "Cupressus"]

,objectid,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Active Growth Period,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL,geometry
262,18578,Cupressus species - other cypress,cupressus species,other cypress,Cupressus,species,NaN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],cupressus species,[N/a],[N/a],[N/a],[N/a],aggregated,NaN,POINT (-75.1686 39.96176)

In [109]:
for idx in range(len(unique_non_specifc_genus_list)):
    aggregate_values(unique_non_specifc_genus_list[idx])

In [112]:
non_specific_pheno = phenos.loc[phenos["Species"] == "species"]

In [113]:
non_specific_pheno

,objectid,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Active Growth Period,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL,geometry
114,16962,Picea species - norway spruce,picea species,norway spruce,Picea,species,PIAB,"[Spring and Summer, Summer]",[No],[Yellow],[No],"[Dark Green, Green]",[Dense],[Dense],[Brown],[No],[Yes],"[Mid Spring, Late Spring]","[Medium, Low, High]",[Summer],"[Fall, Summer]",[No],picea species,"[N/a, Non-flowering]","[N/a, Non-flowering]",[N/a],"[N/a, Evergreen, Colorful, Evergreen]",aggregated,NaN,POINT (-74.99181 40.05301)
191,10,Amelanchier species - other serviceberry,amelanchier species,other serviceberry,Amelanchier,species,NaN,[Spring and Summer],[Yes],[White],[Yes],"[Dark Green, Green]","[Dense, Moderate]",[Porous],"[Red, Purple]",[Yes],[No],"[Mid Spring, Early Spring]","[Medium, High]",[Spring],[Summer],"[Yes, No]",amelanchier species,"[March to April, April, N/a]","[White, N/a]","[Showy, Fragrant, N/a]","[Good Fall, N/a]",aggregated,NaN,POINT (-75.20996 39.98388)
193,40,Prunus species - other cherry,prunus species,other cherry,Prunus,species,NaN,[Spring and Summer],"[No, Yes]",[White],"[Yes, No]",[Green],"[Dense, Moderate]","[Moderate, Porous]","[Red, Black]",[Yes],[No],"[Mid Spring, Early Spring, Spring, Late Spring]","[Medium, High]",[Summer],"[Fall, Summer]","[Yes, No]",prunus species,"[March, April to May, N/a, April, March to Apr...","[White, N/a, Pink, White to pink, Pink to white]","[Showy, Fragrant, N/a, Showy]","[N/a, Good Fall]",aggregated,NaN,POINT (-75.1213 40.02181)
200,65,Malus species - other crabapple,malus species,other crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21236 39.98367)
202,84,Magnolia species - other magnolia,magnolia species,other magnolia,Magnolia,species,NaN,"[Spring and Summer, Spring]","[Yes, No]","[Yellow, White]",[Yes],"[Green, Dark Green]","[Dense, Moderate, Porous]","[Porous, Dense, Moderate]","[Red, Brown, Black]","[Yes, No]","[No, Yes]","[Mid Spring, Spring, Summer]",[Medium],"[Spring, Summer]","[Summer, Winter]",[No],magnolia species,"[April to May, May to June, March, May, N/a]","[Greenish yellow, White, N/a]","[Showy, Fragrant, Showy, N/a]","[Good Fall, Evergreen, N/a]",aggregated,NaN,POINT (-75.20916 39.94819)
203,124,Crataegus species - other hawthorn,crataegus species,other hawthorn,Crataegus,species,NaN,[Spring and Summer],[Yes],"[White, Purple]",[Yes],"[Green, Dark Green, Yellow-Green]","[Dense, Moderate]","[Moderate, Porous]",[Red],[Yes],[No],"[Late Spring, Mid Spring, Early Spring]","[High, Medium]","[Summer, Spring]",[Fall],"[No, Yes]",crataegus species,"[May, N/a, June]","[White, N/a]","[Showy, Fragrant, N/a, Showy]","[Good Fall, N/a]",aggregated,NaN,POINT (-75.20933 39.94716)
204,156,Aesculus species - other buckeye,aesculus species,other buckeye,Aesculus,species,NaN,[Spring and Summer],"[Yes, No]","[Yellow, Green, Red]",[Yes],"[Green, Yellow-Green]",[Dense],[Porous],[Brown],[Yes],[No],"[Late Spring, Mid Spring]",[Medium],"[Summer, Spring]",[Fall],[No],aesculus species,"[N/a, April to May, May]","[N/a, Greenish-yellow, Bright red, White with ...","[N/a, Showy, Fragrant, Showy]","[N/a, Fragrant, Good Fall]",aggregated,NaN,POINT (-75.21076 39.94782)
209,261,Ulmus species - other elm,ulmus species,other elm,Ulmus,species,NaN,[Spring and Summer],"[No, Yes]","[Yellow, Green]",[No],[Green],"[Moderate, Dense]",[Porous],[Brown],"[No, Yes]",[No],"[Early Spring, Late Summer, Mid Spring, Late W...","[Medium, High]",[Spring],[Spring],[No],ulmus species,"[March to April, August to September, N/a]","[Reddish green, Reddish-green, N/a]","[Insignificant, N/a]",[N/a],aggregated,NaN,POINT (-75.21045 39.94855)
212,367,Cornus species - other dogwood,cornus species,other dogwood,Cornus,species,NaN,[Spring and Summer],[Yes],"[White, Yellow]",[Yes],[Green],"[Porous, Dense]","[Porous, Moderate]",[Red],[Yes],[No],"[Early Spring, Mid Spring]","[Medium, High]",[Spring],"[Fall, Summer]","[No, Yes]",cornus species,"[April to May, March, May to June, N/a]","[White (bracts), Yellow, White to pinkish (bra...","[Showy, N/a]","[Good Fall, N/a]",aggregated,NaN,POINT (-75.22201 39.94823)
222,705,Taxus species - yew,taxus species,yew,Taxus,species,NaN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],taxus species,[N/a],[N/a],[N/a],[N/a],aggregated,NaN,POINT (-75.20904 39.98306)
223,772,Salix species - other willow,salix species,other willow,Salix,species,NaN,[Spring and Summer],[No],[Yellow],[No],[Green],"[Moderate, Dense]","[Porous, Moderate]",[White],[No],[No],[Early Spring],[High],[Spring],"[Summer, Spring]",[No],salix species,"[March to April, April to May, N/a]","[Yellowish-green, Silver green, N/a]","[Insignificant, N/a]",[N/a],aggregated,NaN,POINT (-75.21118 39.98364)
224,832,Pinus species - other pine,pinus species,other pine,Pinus,species,NaN,"[Spring, Spring and Summer]",[No],"[Yellow, Brown, Green, Red]",[No],"[Green, Yellow-Green, Dark Green]","[Dense, Moderate]","[Dense, Moderate]","[Brown, Purple]","[No, Yes]",[Yes],"[Late Spring, Spring, Mid Spring]","[High, Medium]",[Summer],[Fall],[No],pinus species,"[Non-flowering, N/a]","[Non-flowering, N/a]",[N/a],"[Evergreen, N/a, Colorful, Evergreen]",aggregated,NaN,POINT (-75.21423 39.98326)
227,883,Carya species - other hickory,carya species,other hickory,Carya,species,NaN,[Spring and Summer],"[Yes, No]","[Green, Yellow]","[No, Yes]","[Green, Yellow-Green]","[Dense, Moderate]",[Porous],[Brown],[Yes],[No],"[Mid Spring, Early Spring, Late Spring]","[Medium, High, Low]",[Summer],[Fall],[Yes],carya species,"[April to May, N/a]","[Green, Yellowish-green, N/a, Greenish-yellow]","[Insignificant, N/a, Showy]","[N/a, Good Fall, Fragrant, Good Fall]",aggregated,NaN,POINT (-75.21394 39.98223)
230,1268,Acer species - other maple,acer species,other maple,Acer,species,NaN,[Spring and Summer],"[Yes, No]","[White, Yellow, Green, Red]","[No, Yes]","[Green, Yellow-Green]","[Dense, Moderate]","[Moderate, Porous]","[Brown, Green, Red]","[Yes, No]",[No],"[Mid Spring, Early Spring, Late Spring]","[High, Medium]","[Summer, Spring]","[Fall, Summer, Spring]","[No, Yes]",acer species,"[N/a, March to April, May, March, April, April...","[N/a, Greenish-yellow, Yellow, Yellow green, R...","[N/a, Insignificant, Showy]","[N/a, Good Fall]",aggregated,NaN,POINT (-75.17707 40.05114)
234,1796,Quercus species - other oak,quercus species,other oak,Quercus,species,NaN,[Spring and Summer],[Yes],"[Green, Yellow]",[No],"[Dark Green, Green]","[Dense, Moderate]","[Porous, Moderate]",[Brown],"[Yes, No]",[No],"[Mid Spring, Early Spring, Late Spring, Spring]","[Medium, High, Low]","[Summer, Fall, Spring]","[Fall, Summer]",[No],quercus species,"[March to April, May, April, April to May, N/a]","[Yellowish-green, Green (female)Red (male), N/...","[Insignificant, N/a]","[Good Fall, N/a]",aggregated,NaN,POINT (-75.16901 40.02086)
235,1831,Abies species - other fir,abies species,other fir,Abies,species,NaN,[Spring and Summer],[No],"[Yellow, Purple]",[No],"[Green, Dark Green]","[Dense, Moderate]","[Dense, Moderate]",[Brown],"[No, Yes]",[Yes],"[Mid Summer, Mid Spring]",[Medium],"[Fall, Spring]",[Fall],[No],abies species,"[Non-flowering, N/a]","[Non-flowering, N/a]",[N/a],"[Fragrant, Evergreen, N/a]",aggregated,NaN,POINT (-75.18114 40.02538)
240,4485,Fraxinus species - other ash,fraxinus species,other ash,Fraxinus,species,NaN,[Spring and Summer],"[Yes, No]","[Yellow, White, Green]",[No],"[Green, Yellow-Green]",[Dense],"[Porous, Moderate]",[Brown],"[Yes, No]",[No],"[Mid Spring, Early Spring, Late Spring]","[High, Low]","[Summer, Spring]","[Fall, Summer]",[No],fraxinus species,"[April to May, N/a]","[Purplish, N/a, Purple]","[Showy, N/a]","[Good Fall, N/a]",aggregated,NaN,POINT (-75.05936 40.08777)
242,4620,Tilia species - other linden,tilia species,other linden,Tilia,species,NaN,[Spring and Summer],[Yes],[Yellow],"[Yes, No]",[Green],[Dense],[Porous],[Brown],[No],[No],"[Late Spring, Early Summer]",[High],[Summer],[Fall],[No],tilia species,"[June, June to July, N/a]","[Pale yellow, N/a]","[Showy, Fragrant, N/a]","[N/a, Colorful]",aggregated,NaN,POINT (-75.1712 39.91524)
244,5034,Picea species - other spruce,picea species,other spruce,Picea,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,picea species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.24744 39.96538)
246,7017,Ilex species - other holly,ilex species,other holly,Ilex,species,NaN,[Spring and Summer],[Yes],[Yellow],[No],[Green],[Dense],[Dense],[Red],[Yes],[Yes],[Mid Spring],[Low],[Summer],[Fall],[No],ilex species,"[May, N/a]","[Creamy white, N/a]","[Insignificant, N/a]","[Evergreen, N/a]",aggregated,NaN,POINT (-75.17152 39.94926)
250,9477,Poplar species - other poplar,poplar species,other poplar,Poplar,species,NaN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],poplar species,[N/a],[N/a],[N/a],[N/a],aggregated,NaN,POINT (-74.99859 40.06203)
251,10542,Fagus species - other beech,fagus species,other beech,Fagus,species,NaN,[Spring and Summer],[Yes],[Yellow],[No],[Green],[Dense],[Dense],[Brown],[No],[No],[Mid Spring],[Medium],[Summer],[Fall],[Yes],fagus species,"[April to May, N/a]","[Yellowish-green, N/a]","[Insignificant, N/a]","[Good Fall, N/a]",aggregated,NaN,POINT (-75.0657 40.02434)
255,11496,Castanea species - other chestnut,castanea species,other chestnut,Castanea,species,NaN,"[Spring, Spring and Summer]","[Yes, No]","[White, Yellow]","[No, Yes]","[Yellow-Green, Green]","[Dense, Porous]","[Porous, Moderate]",[Brown],[Yes],[No],"[Early Summer, Mid Spring, Spring]","[Medium, Low]",[Summer],[Fall],[Yes],castanea species,"[June, N/a]","[Yellow-white, Yellowish-white, N/a]","[Insignificant, Showy, Fragrant, N/a]","[N/a, Good Fall]",aggregated,NaN,POINT (-75.18779 39.99251)
257,12024,Stewartia species - other stewartia,stewartia species,other stewartia,Stewartia,species,NaN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],stewartia species,[N/a],[N/a],[N/a],[N/a],aggregated,NaN,POINT (-75.17973 39.966)
262,18578,Cupressus species - other cypress,cupressus species,other cypress,Cupressus,species,NaN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],cupressus species,[N/a],[N/a],[N/a],[N/a],aggregated,NaN,POINT (-75.1686 39.96176)
266,31517,Betula species - other birch,betula species,other birch,Betula,species,NaN,[Spring and Summer],"[No, Yes]","[Yellow, Brown]","[No, Yes]",[Green],"[Dense, Moderate]",[Porous],[Brown],[No],[No],"[Late Spring, Mid Spring]","[Medium, Low, High]","[Summer, Spring]","[Summer, Fall, Spring]","[Yes, No]",betula species,"[April to May, March to April, April, N/a]","[Female catkins green, male catkins mature fro...","[N/a, Insignificant, Showy]","[Good Fall, Fragrant, Good Fall, N/a]",aggregated,NaN,POINT (-75.25763 39.97739)
269,37268,Malus species - harvest gold crabapple,malus species,harvest gold crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21556 40.04068)
275,38713,Malus species - spring snow crabapple,malus species,spring snow crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.17545 39.96941)
277,40242,Alnus species – other alder,alnus species,other alder,Alnus,species,NaN,[Spring and Summer],[No],[Purple],[No],[Green],[Moderate],[Porous],[Brown],[Yes],[No],[Mid Spring],[Low],[Summer],[Fall],[No],alnus species,"[March, N/a]","[Reddish-brown (male), purple (female), N/a]","[Showy, N/a]",[N/a],aggregated,NaN,POINT (-75.12406 39.98135)
280,46170,Malus species - snowdrift crabapple,malus species,snowdrift crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.16428 39.93148)
282,48559,Sorbus species - other mountain ash,sorbus species,other mountain ash,Sorbus,species,NaN,[Spring and Summer],[Yes],[White],[Yes],[Green],[Moderate],[Porous],[Orange],[Yes],[No],"[Early Summer, Late Spring]",[High],[Summer],[Fall],[No],sorbus species,"[May, N/a]","[White, N/a]","[Showy, N/a]","[N/a, Good Fall]",aggregated,NaN,POINT (-75.15008 39.93725)
288,52961,Malus species - pink spires crabapple,malus species,pink spires crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.16917 39.94613)
289,69306,Malus species - sugar tyme crabapple,malus species,sugar tyme crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.15918 39.96229)
290,78656,Rosa species - other rose,rosa species,other rose,Rosa,species,NaN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],rosa species,[N/a],[N/a],[N/a],[N/a],aggregated,NaN,POINT (-75.14111 39.99438)
292,148593,Malus species - indian summer crabapple,malus species,indian summer crabapple,Malus,species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,malus species,N/a,N/a,N/a,N/a,no exact match,NaN,POINT (-75.21815 39.94158)

In [ ]:
phenos = phenos.drop(columns=["objectid", "geometry", "Detail URL"])

KeyError: "['objectid', 'geometry', 'Detail URL'] not found in axis"

In [ ]:
#phenos.to_csv("/Users/prince/philly-tree-mapper/data/processed/philly_species_pheno.csv", index=False)