In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
pd.set_option('display.max_columns', None)

In [ ]:
phenos = pd.read_csv("/Users/prince/philly-tree-mapper/data/processed/philly_species_pheno_DOY.csv")

In [3]:
phenos.groupby("Status").size()

Status
fuzzy (sci=0.63, com=1.00)      1
fuzzy (sci=0.73, com=1.00)      1
fuzzy (sci=0.74, com=1.00)      1
fuzzy (sci=0.76, com=1.00)      2
fuzzy (sci=0.78, com=0.96)      1
fuzzy (sci=0.78, com=1.00)      1
manual search                   3
matched                       205
no exact match                 35
no results container           42
single result                   2
dtype: int64

In [4]:
phenos["MOBOT match"] = ~phenos["Detail URL"].isna()

In [5]:
phenos = phenos.drop(columns=["Status"])

In [6]:
phenos["USDA match"] = ~phenos["plant_code"].isna()

In [7]:
phenos.groupby("Flower").size()

Flower
Fragrant, Insignificant      1
Insignificant               92
N/a                        105
Showy                       50
Showy, Fragrant             43
Showy, Good Cut              3
dtype: int64

In [8]:
phenos.groupby("Morphology/Physiology | Flower Conspicuous").size()

Morphology/Physiology | Flower Conspicuous
No     124
Yes     65
dtype: int64

In [9]:
def mobot_flower_visible(desc):
    if desc == "N/a":
           return np.nan
    elif desc == "Insignificant" or desc == "Fragrant, Insignificant":
        return False
    else:
        return True

In [10]:
def usda_flower_visible(desc):
    if desc != desc:
        return np.nan
    elif desc == "No":
        return False
    else:
        return True

In [11]:
def flower_visible(row):
    mobot = mobot_flower_visible(row["Flower"])
    usda = usda_flower_visible(row["Morphology/Physiology | Flower Conspicuous"])
    if mobot is True or usda is True:
        return True
    elif mobot != mobot and usda != usda:
        return np.nan
    else:
        return False

In [12]:
phenos["Visible_Flowers"] = phenos.apply(lambda row: flower_visible(row), axis=1)

In [13]:
phenos = phenos.drop(columns="Unnamed: 0")

In [14]:
phenos.loc[(phenos["Morphology/Physiology | Leaf Retention"] == "No") & (phenos["Morphology/Physiology | Foliage Porosity Winter"] != "Porous")]

,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Detail URL,bloom_range_DOY,fruit_range_DOY,Type,MOBOT match,USDA match,Visible_Flowers
2,Acer ginnala - amur maple,acer ginnala,amur maple,Acer,ginnala,ACGI,Yes,White,No,Green,Dense,Moderate,Brown,Yes,No,Mid Spring,High,Summer,Fall,No,acer ginnala,N/a,N/a,N/a,N/a,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 172, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False
6,Acer platanoides - crimson king norway maple,acer platanoides,crimson king norway maple,Acer,platanoides,ACPL,Yes,Green,No,Green,Dense,Moderate,Brown,Yes,No,Early Spring,High,Summer,Fall,No,acer platanoides,March to April,Yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
7,Acer platanoides - norway maple,acer platanoides,norway maple,Acer,platanoides,ACPL,Yes,Green,No,Green,Dense,Moderate,Brown,Yes,No,Early Spring,High,Summer,Fall,No,acer platanoides,March to April,Yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
25,Ailanthus altissima - tree of heaven,ailanthus altissima,tree of heaven,Ailanthus,altissima,AIAL,No,Green,Yes,Green,Moderate,Moderate,Yellow,Yes,No,Late Spring,High,Summer,Fall,No,ailanthus altissima,June,Greenish,"Showy, Fragrant",Fragrant,https://www.missouribotanicalgarden.org/PlantF...,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True
45,Castanea mollissima - chinese chestnut,castanea mollissima,chinese chestnut,Castanea,mollissima,CAMO83,Yes,Yellow,Yes,Green,Porous,Moderate,Brown,Yes,No,Mid Spring,Medium,Summer,Fall,Yes,castanea mollissima,June,Yellowish-white,"Showy, Fragrant",Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True
60,Cornus mas - corneliancherry dogwood,cornus mas,corneliancherry dogwood,Cornus,mas,COMA21,Yes,Yellow,Yes,Green,Dense,Moderate,Red,Yes,No,Mid Spring,High,Spring,Summer,Yes,cornus mas,March,Yellow,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,True
61,Crataegus crus-galli - cockspur hawthorn,crataegus crus-galli,cockspur hawthorn,Crataegus,crus-galli,CRCR2,Yes,White,Yes,Green,Dense,Moderate,Red,Yes,No,Late Spring,High,Summer,Fall,No,crataegus crus-galli,May,White,"Showy, Fragrant",Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True
64,Crataegus monogyna - english hawthorn,crataegus monogyna,english hawthorn,Crataegus,monogyna,CRMO3,Yes,Purple,Yes,Dark Green,Dense,Moderate,Red,Yes,No,Mid Spring,High,Summer,Fall,No,crataegus monogyna,N/a,N/a,N/a,N/a,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 172, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,True
66,Crataegus viridis - winter king hawthorn,crataegus viridis,winter king hawthorn,Crataegus,viridis,CRVI2,Yes,White,Yes,Yellow-Green,Dense,Moderate,Red,Yes,No,Early Spring,Medium,Spring,Fall,Yes,crataegus viridis,May,White,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Tree,True,True,True
67,Crataegus viridis - green hawthorn,crataegus viridis,green hawthorn,Crataegus,viridis,CRVI2,Yes,White,Yes,Yellow-Green,Dense,Moderate,Red,Yes,No,Early Spring,Medium,Spring,Fall,Yes,crataegus viridis,May,White,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Tree,True,True,True
69,Elaeagnus umbellata - autumn olive,elaeagnus umbellata,autumn olive,Elaeagnus,umbellata,ELUM,Yes,Yellow,Yes,White-Gray,Dense,Moderate,Red,Yes,No,Early Spring,High,Summer,Fall,Yes,elaeagnus umbellata,April to June,Slivery white to dull yellow,"Showy, Fragrant",N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Deciduous shrub,True,True,True
71,Fagus grandifolia - american beech,fagus grandifolia,american beech,Fagus,grandifolia,FAGR,Yes,Yellow,No,Green,Dense,Dense,Brown,No,No,Mid Spring,Medium,Summer,Fall,Yes,fagus grandifolia,April to May,Yellowish-green,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
77,Fraxinus pennsylvanica - green ash,fraxinus pennsylvanica,green ash,Fraxinus,pennsylvanica,FRPE,Yes,Green,No,Yellow-Green,Dense,Moderate,Brown,No,No,Late Spring,High,Spring,Summer,No,fraxinus pennsylvanica,April to May,Purple,N/a,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,False
78,Fraxinus pennsylvanica - summit green ash,fraxinus pennsylvanica,summit green ash,Fraxinus,pennsylvanica,FRPE,Yes,Green,No,Yellow-Green,Dense,Moderate,Brown,No,No,Late Spring,High,Spring,Summer,No,fraxinus pennsylvanica,April to May,Purple,N/a,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,False
81,Gleditsia triacanthos - honeylocust,gleditsia triacanthos,honeylocust,Gleditsia,triacanthos,GLTR,Yes,Yellow,No,Green,Dense,Moderate,Green,Yes,No,Late Spring,High,Spring,Fall,No,gleditsia triacanthos,May to June,Greenish-yellow,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Tree,True,True,True
91,Juniperus virginiana - eastern redcedar,juniperus virginiana,eastern redcedar,Juniperus,virginiana,JUVI,No,Green,No,Green,Dense,Dense,White,Yes,No,Late Spring,Medium,Summer,Fall,No,juniperus virginiana,Non-flowering,Non-flowering,N/a,Evergreen,https://www.missouribotanicalgarden.org/PlantF...,NaN,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Needled evergreen,True,True,False
133,Prunus americana - american plum,prunus americana,american plum,Prunus,americana,PRAM,No,White,Yes,Green,Dense,Moderate,Red,Yes,No,Mid Spring,Medium,Summer,Fall,Yes,prunus americana,March,White,"Showy, Fragrant",N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True
141,Pyrus calleryana - callery pear,pyrus calleryana,callery pear,Pyrus,calleryana,PYCA80,Yes,White,Yes,Green,Dense,Moderate,Black,Yes,No,Early Spring,Medium,Spring,Summer,No,pyrus calleryana,April,White,Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,True
142,Pyrus calleryana - bradford pear,pyrus calleryana,bradford pear,Pyrus,calleryana,PYCA80,Yes,White,Yes,Green,Dense,Moderate,Black,Yes,No,Early Spring,Medium,Spring,Summer,No,pyrus calleryana,April,White,Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,True
159,Quercus palustris - pin oak,quercus palustris,pin oak,Quercus,palustris,QUPA2,Yes,Yellow,No,Green,Dense,Moderate,Brown,No,No,Spring,Medium,Summer,Fall,No,quercus palustris,April,Yellowish-green,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
171,Salix babylonica - weeping willow,salix babylonica,weeping willow,Salix,babylonica,SASE10,No,Yellow,No,Green,Dense,Moderate,White,No,No,Early Spring,High,Spring,Spring,No,salix babylonica,April to May,Silver green,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,False
174,Taxodium distichum - baldcypress,taxodium distichum,baldcypress,Taxodium,distichum,TADI2,Yes,Purple,No,Green,Dense,Moderate,Brown,No,No,Mid Spring,Low,Summer,Fall,No,taxodium distichum,Non-flowering,Non-flowering,N/a,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,NaN,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False

In [15]:
phenos.groupby("Morphology/Physiology | Foliage Porosity Winter").size()

Morphology/Physiology | Foliage Porosity Winter
Dense        22
Moderate     24
Porous      143
dtype: int64

In [16]:
phenos.groupby("Morphology/Physiology | Foliage Porosity Summer", as_index=False).size()

  Morphology/Physiology | Foliage Porosity Summer  size
0                                           Dense   124
1                                        Moderate    58
2                                          Porous     7

In [17]:
phenos.groupby("Morphology/Physiology | Foliage Porosity Winter", as_index=False)["Morphology/Physiology | Leaf Retention"].value_counts()

,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Leaf Retention,count
0,Dense,Yes,20
1,Dense,No,2
2,Moderate,No,20
3,Moderate,Yes,4
4,Porous,No,143

In [18]:
phenos.loc[(phenos["Morphology/Physiology | Foliage Porosity Winter"] == "Moderate") & (phenos["Morphology/Physiology | Leaf Retention"] == "Yes")]

,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Detail URL,bloom_range_DOY,fruit_range_DOY,Type,MOBOT match,USDA match,Visible_Flowers
1,Abies fraseri - fraser fir,abies fraseri,fraser fir,Abies,fraseri,ABFR,No,Purple,No,Dark Green,Moderate,Moderate,Brown,Yes,Yes,Mid Spring,Medium,Spring,Fall,No,abies fraseri,Non-flowering,N/a,N/a,"Fragrant, Evergreen",https://www.missouribotanicalgarden.org/PlantF...,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Needled evergreen,True,True,False
106,Magnolia virginiana - sweetbay magnolia,magnolia virginiana,sweetbay magnolia,Magnolia,virginiana,MAVI2,No,White,Yes,Dark Green,Moderate,Moderate,Black,Yes,Yes,Summer,Medium,Summer,Winter,No,magnolia virginiana,May to June,White,"Showy, Fragrant",N/a,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True
119,Pinus resinosa - red pine,pinus resinosa,red pine,Pinus,resinosa,PIRE,No,Brown,No,Yellow-Green,Moderate,Moderate,Purple,Yes,Yes,Spring,Medium,Summer,Fall,No,pinus resinosa,Non-flowering,Non-flowering,N/a,Evergreen,https://www.missouribotanicalgarden.org/PlantF...,NaN,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Needled evergreen,True,True,False
120,Pinus rigida - pitch pine,pinus rigida,pitch pine,Pinus,rigida,PIRI,No,Green,No,Yellow-Green,Moderate,Moderate,Brown,Yes,Yes,Spring,High,Summer,Fall,No,pinus rigida,N/a,N/a,N/a,N/a,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 172, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False

STARTING POINT FOR TOMORROW. ADD BACK TYPE TO RESCRAPE MOBOT FOR TYPE OF TREE IT IS.

In [19]:

# For moderates, leaf retention is a good indicator of whether or not it will be bare.
# Moderate porosity + Leaf Retention == "No" -> Decidious tree, will be bare
# Moderate porosity + Leaf Retention == "Yes" -> Evergreen tree, all leaves there
    #Notable exception is Magnolia virginiana, semi evergreen. Loses leaves depending on climate, will treat it as decidous in philly
    #This is kinda hacky
def usda_winter_leaves(row):
    """Put in row of pheno df and return True if leaves in winter, and false if no leaves in winter
    return NaN if inconclusive or no data"""
    leaf_retention = row["Morphology/Physiology | Leaf Retention"]
    winter_foliage = row["Morphology/Physiology | Foliage Porosity Winter"]
    name = row["scientific_name"]
    if name == "magnolia virginiana":
        return False
    elif leaf_retention != leaf_retention or winter_foliage != winter_foliage:
        return np.nan
    elif winter_foliage == "Dense":
        return True
    elif winter_foliage == "Porous":
        return False
    elif winter_foliage == "Moderate" and leaf_retention == "No":
        return False
    elif winter_foliage == "Moderate" and leaf_retention == "Yes":
        return True

In [20]:
def mobot_winter_leaves(row):
    """Put in row of pheno df and return true if there are leaves in the winter
    false if not, return NaN if inconclusive"""
    tree_type = row["Type"]
    leaf = row["Leaf"]
    mobot_match = row["MOBOT match"]
    if mobot_match is False:
        return np.nan
    elif tree_type == "Broadleaf evergreen" or tree_type == "Needled evergreen":
        return True
    elif leaf == "Colorful, Evergreen"  or leaf == "Evergreen" or leaf == "Fragrant, Evergreen":
        return True
    else:
        return np.nan

In [21]:
phenos.loc[phenos["MOBOT match"] == True]

,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Detail URL,bloom_range_DOY,fruit_range_DOY,Type,MOBOT match,USDA match,Visible_Flowers
0,Abies balsamea - balsam fir,abies balsamea,balsam fir,Abies,balsamea,ABBA,No,Yellow,No,Green,Dense,Dense,Brown,No,Yes,Mid Summer,Medium,Fall,Fall,No,abies balsamea,Non-flowering,Non-flowering,N/a,"Fragrant, Evergreen",https://www.missouribotanicalgarden.org/PlantF...,NaN,"[244, 245, 246, 247, 248, 249, 250, 251, 252, ...",Needled evergreen,True,True,False
1,Abies fraseri - fraser fir,abies fraseri,fraser fir,Abies,fraseri,ABFR,No,Purple,No,Dark Green,Moderate,Moderate,Brown,Yes,Yes,Mid Spring,Medium,Spring,Fall,No,abies fraseri,Non-flowering,N/a,N/a,"Fragrant, Evergreen",https://www.missouribotanicalgarden.org/PlantF...,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Needled evergreen,True,True,False
3,Acer negundo - boxelder,acer negundo,boxelder,Acer,negundo,ACNE2,Yes,White,No,Green,Dense,Porous,Brown,Yes,No,Early Spring,High,Summer,Fall,Yes,acer negundo,March to April,Greenish-yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
6,Acer platanoides - crimson king norway maple,acer platanoides,crimson king norway maple,Acer,platanoides,ACPL,Yes,Green,No,Green,Dense,Moderate,Brown,Yes,No,Early Spring,High,Summer,Fall,No,acer platanoides,March to April,Yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
7,Acer platanoides - norway maple,acer platanoides,norway maple,Acer,platanoides,ACPL,Yes,Green,No,Green,Dense,Moderate,Brown,Yes,No,Early Spring,High,Summer,Fall,No,acer platanoides,March to April,Yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Acer truncatum - purpleblow maple,acer truncatum,purpleblow maple,Acer,truncatum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,acer truncatum,April,Greenish yellow,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...",NaN,Tree,True,False,False
278,Prunus subhirtella - snow goose cherry,prunus subhirtella,snow goose cherry,Prunus,subhirtella,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,prunus subhirtella,April,Pink to white,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...",NaN,Tree,True,False,True
284,Acer triflorum – three flowered maple,acer triflorum,three flowered maple,Acer,triflorum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,acer triflorum,April,Greenish yellow,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...",NaN,Tree,True,False,False
285,Carpinus betulus - fastigiate hornbeam,carpinus betulus,fastigiate hornbeam,Carpinus,betulus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,carpinus betulus,March,Yellow (male) and green (female),Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",NaN,Tree,True,False,False
287,Quercus robur - columnar english oak,quercus robur,columnar english oak,Quercus,robur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,quercus robur,April,Yellowish-green,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...",NaN,Tree,True,False,False

In [22]:
def winter_leaves(row):
    """Takes one row of pheno df and returns True if it has leaves in winter, false if not
    NaN if inconclusive. Does this by using MOBOT and USDA data"""
    mobot = mobot_winter_leaves(row)
    usda = usda_winter_leaves(row)
    if mobot is True or usda is True:
        return True
    elif mobot != mobot and usda != usda:
        return np.nan
    else:
        return False

In [23]:
phenos["Winter_Leaves"] = phenos.apply(lambda row: winter_leaves(row), axis=1)

Even within the same Genus, some trees are deciduous some are evergreen
Unwise to make genus level aggregations, simply not true some of the time. 
Go through and look shit up by hand?
Why not make a more customized dataset lol only have a few misses

In [24]:
# Find if shit change colors in the fall
def usda_fall_conspic(row):
    """Function takes row from phenos. if fall conspic according to USDA return TRUE if not 
    return False, if no data NaN"""
    conspic = row["Morphology/Physiology | Fall Conspicuous"]
    if conspic == "Yes":
        return True
    elif conspic == "No":
        return False
    else:
        return np.nan
def mobot_fall_conspic(row):
    """Take row from phenos. if fall conspic according to mobot return true
    if not return false, if no data NaN"""
    conspic = row["Leaf"]
    if conspic == "Colorful, Good Fall" or conspic == "Fragrant, Good Fall" or conspic == "Good Fall":
        return True
    elif conspic == "N/a":
        return np.nan
    else:
        return False
    
def fall_conspic(row):
    """Combine data from usda and mobot to determine if tree is conspicuous in fall"""
    mobot = mobot_fall_conspic(row)
    usda = usda_fall_conspic(row)
    if usda != usda and mobot != mobot:
        return np.nan
    elif usda is True or mobot is True:
        return True
    else:
        return False

In [25]:
phenos["Fall_Conspic"] = phenos.apply(lambda row: fall_conspic(row), axis=1)

In [26]:
phenos.groupby("Morphology/Physiology | Flower Color", as_index=False).size()

  Morphology/Physiology | Flower Color  size
0                                 Blue     1
1                                Brown     4
2                                Green    36
3                               Orange     1
4                               Purple    11
5                                  Red    13
6                                White    41
7                               Yellow    74

In [27]:
mobot_colors = phenos.groupby("Bloom Description", as_index=False).size().sort_values(by="size", ascending=False)

In [28]:
mobot_usda_matched = phenos.loc[(phenos["MOBOT match"] == True) & (phenos["USDA match"] == True)]

In [29]:
mobot_usda_matched = mobot_usda_matched[["scientific_name","Bloom Description", "Morphology/Physiology | Flower Color"]]

In [30]:
phenos[0:51]

,tree_name,scientific_name,common_name,Genus,Species,plant_code,Morphology/Physiology | Fall Conspicuous,Morphology/Physiology | Flower Color,Morphology/Physiology | Flower Conspicuous,Morphology/Physiology | Foliage Color,Morphology/Physiology | Foliage Porosity Summer,Morphology/Physiology | Foliage Porosity Winter,Morphology/Physiology | Fruit/Seed Color,Morphology/Physiology | Fruit/Seed Conspicuous,Morphology/Physiology | Leaf Retention,Reproduction | Bloom Period,Reproduction | Fruit/Seed Abundance,Reproduction | Fruit/Seed Period Begin,Reproduction | Fruit/Seed Period End,Suitability/Use | Palatable Human,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Detail URL,bloom_range_DOY,fruit_range_DOY,Type,MOBOT match,USDA match,Visible_Flowers,Winter_Leaves,Fall_Conspic
0,Abies balsamea - balsam fir,abies balsamea,balsam fir,Abies,balsamea,ABBA,No,Yellow,No,Green,Dense,Dense,Brown,No,Yes,Mid Summer,Medium,Fall,Fall,No,abies balsamea,Non-flowering,Non-flowering,N/a,"Fragrant, Evergreen",https://www.missouribotanicalgarden.org/PlantF...,NaN,"[244, 245, 246, 247, 248, 249, 250, 251, 252, ...",Needled evergreen,True,True,False,True,False
1,Abies fraseri - fraser fir,abies fraseri,fraser fir,Abies,fraseri,ABFR,No,Purple,No,Dark Green,Moderate,Moderate,Brown,Yes,Yes,Mid Spring,Medium,Spring,Fall,No,abies fraseri,Non-flowering,N/a,N/a,"Fragrant, Evergreen",https://www.missouribotanicalgarden.org/PlantF...,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Needled evergreen,True,True,False,True,False
2,Acer ginnala - amur maple,acer ginnala,amur maple,Acer,ginnala,ACGI,Yes,White,No,Green,Dense,Moderate,Brown,Yes,No,Mid Spring,High,Summer,Fall,No,acer ginnala,N/a,N/a,N/a,N/a,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 172, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False,False,True
3,Acer negundo - boxelder,acer negundo,boxelder,Acer,negundo,ACNE2,Yes,White,No,Green,Dense,Porous,Brown,Yes,No,Early Spring,High,Summer,Fall,Yes,acer negundo,March to April,Greenish-yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
4,Acer nigrum - black maple,acer nigrum,black maple,Acer,nigrum,ACNI5,Yes,Yellow,No,Green,Dense,Porous,Brown,No,No,Late Spring,Medium,Summer,Fall,Yes,acer nigrum,N/a,N/a,N/a,N/a,NaN,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False,False,True
5,Acer pensyvanicum - striped maple,acer pensyvanicum,striped maple,Acer,pensyvanicum,ACPE,Yes,Yellow,No,Green,Moderate,Porous,Brown,No,No,Late Spring,Medium,Summer,Fall,No,acer pensyvanicum,N/a,N/a,N/a,N/a,NaN,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False,False,True
6,Acer platanoides - crimson king norway maple,acer platanoides,crimson king norway maple,Acer,platanoides,ACPL,Yes,Green,No,Green,Dense,Moderate,Brown,Yes,No,Early Spring,High,Summer,Fall,No,acer platanoides,March to April,Yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
7,Acer platanoides - norway maple,acer platanoides,norway maple,Acer,platanoides,ACPL,Yes,Green,No,Green,Dense,Moderate,Brown,Yes,No,Early Spring,High,Summer,Fall,No,acer platanoides,March to April,Yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
8,Acer pseudoplatanus - sycamore maple,acer pseudoplatanus,sycamore maple,Acer,pseudoplatanus,ACPS,No,Green,No,Yellow-Green,Dense,Porous,Green,Yes,No,Late Spring,High,Spring,Summer,No,acer pseudoplatanus,May,Yellow green,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,False,False,False
9,Acer rubrum - red maple,acer rubrum,red maple,Acer,rubrum,ACRU,Yes,Red,Yes,Green,Dense,Porous,Red,Yes,No,Early Spring,High,Spring,Spring,Yes,acer rubrum,March to April,"Red, sometimes yellow",Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,True
10,Acer rubrum - red sunset red maple,acer rubrum,red sunset red maple,Acer,rubrum,ACRU,Yes,Red,Yes,Green,Dense,Porous,Red,Yes,No,Early Spring,High,Spring,Spring,Yes,acer rubrum,March to April,"Red, sometimes yellow",Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,True
11,Acer rubrum - autumn flame red maple,acer rubrum,autumn flame red maple,Acer,rubrum,ACRU,Yes,Red,Yes,Green,Dense,Porous,Red,Yes,No,Early Spring,High,Spring,Spring,Yes,acer rubrum,March to April,"Red, sometimes yellow",Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,True
12,Acer rubrum - bowhall red maple,acer rubrum,bowhall red maple,Acer,rubrum,ACRU,Yes,Red,Yes,Green,Dense,Porous,Red,Yes,No,Early Spring,High,Spring,Spring,Yes,acer rubrum,March to April,"Red, sometimes yellow",Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,True
13,Acer rubrum - karpick red maple,acer rubrum,karpick red maple,Acer,rubrum,ACRU,Yes,Red,Yes,Green,Dense,Porous,Red,Yes,No,Early Spring,High,Spring,Spring,Yes,acer rubrum,March to April,"Red, sometimes yellow",Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,True
14,Acer rubrum - october glory red maple,acer rubrum,october glory red maple,Acer,rubrum,ACRU,Yes,Red,Yes,Green,Dense,Porous,Red,Yes,No,Early Spring,High,Spring,Spring,Yes,acer rubrum,March to April,"Red, sometimes yellow",Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,True
15,Acer saccharinum - silver maple,acer saccharinum,silver maple,Acer,saccharinum,ACSA2,Yes,Yellow,Yes,Green,Dense,Porous,Brown,Yes,No,Early Spring,High,Summer,Fall,Yes,acer saccharinum,March,Greenish-yellow,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True
16,Acer saccharum - sugar maple,acer saccharum,sugar maple,Acer,saccharum,ACSA3,Yes,Green,No,Green,Dense,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,Yes,acer saccharum,April,Greenish,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
17,Acer saccharum - columnar sugar maple,acer saccharum,columnar sugar maple,Acer,saccharum,ACSA3,Yes,Green,No,Green,Dense,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,Yes,acer saccharum,April,Greenish,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
18,Acer saccharum - legacy sugar maple,acer saccharum,legacy sugar maple,Acer,saccharum,ACSA3,Yes,Green,No,Green,Dense,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,Yes,acer saccharum,April,Greenish,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
19,Acer saccharum - goldspire sugar maple,acer saccharum,goldspire sugar maple,Acer,saccharum,ACSA3,Yes,Green,No,Green,Dense,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,Yes,acer saccharum,April,Greenish,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
20,Acer saccharum - green mountain sugar maple,acer saccharum,green mountain sugar maple,Acer,saccharum,ACSA3,Yes,Green,No,Green,Dense,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,Yes,acer saccharum,April,Greenish,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
21,Acer saccharum - bonfire sugar maple,acer saccharum,bonfire sugar maple,Acer,saccharum,ACSA3,Yes,Green,No,Green,Dense,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,Yes,acer saccharum,April,Greenish,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
22,Aesculus octandra - yellow buckeye,aesculus octandra,yellow buckeye,Aesculus,octandra,AEFL,Yes,Yellow,Yes,Green,Dense,Porous,Brown,Yes,No,Late Spring,Medium,Summer,Fall,No,aesculus octandra,N/a,N/a,N/a,N/a,NaN,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,True,False,True
23,Aesculus glabra - ohio buckeye,aesculus glabra,ohio buckeye,Aesculus,glabra,AEGL,Yes,Green,Yes,Green,Dense,Porous,Brown,Yes,No,Mid Spring,Medium,Spring,Fall,No,aesculus glabra,April to May,Greenish-yellow,"Showy, Fragrant","Fragrant, Good Fall",https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 325, ...",Tree,True,True,True,False,True
24,Aesculus pavia - red buckeye,aesculus pavia,red buckeye,Aesculus,pavia,AEPA,No,Red,Yes,Yellow-Green,Dense,Porous,Brown,Yes,No,Late Spring,Medium,Summer,Fall,No,aesculus pavia,April to May,Bright red,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Deciduous shrub,True,True,True,False,False
25,Ailanthus altissima - tree of heaven,ailanthus altissima,tree of heaven,Ailanthus,altissima,AIAL,No,Green,Yes,Green,Moderate,Moderate,Yellow,Yes,No,Late Spring,High,Summer,Fall,No,ailanthus altissima,June,Greenish,"Showy, Fragrant",Fragrant,https://www.missouribotanicalgarden.org/PlantF...,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,False
26,Alnus glutinosa - european alder,alnus glutinosa,european alder,Alnus,glutinosa,ALGL2,No,Purple,No,Green,Moderate,Porous,Brown,Yes,No,Mid Spring,Low,Summer,Fall,No,alnus glutinosa,March,"Reddish-brown (male), purple (female)",Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,False
27,Albizia julibrissin - mimosa,albizia julibrissin,mimosa,Albizia,julibrissin,ALJU,No,White,Yes,White-Gray,Porous,Porous,Brown,Yes,No,Mid Summer,High,Summer,Fall,No,albizia julibrissin,June to July,Pink,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,False
28,Amelanchier arborea - downy serviceberry,amelanchier arborea,downy serviceberry,Amelanchier,arborea,AMAR3,Yes,White,Yes,Dark Green,Dense,Porous,Red,Yes,No,Mid Spring,Medium,Spring,Summer,Yes,amelanchier arborea,March to April,White,"Showy, Fragrant",Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,True,False,True
29,Amelanchier laevis - allegheny serviceberry,amelanchier laevis,allegheny serviceberry,Amelanchier,laevis,AMLA,Yes,White,Yes,Green,Moderate,Porous,Purple,Yes,No,Early Spring,High,Spring,Summer,No,amelanchier laevis,April,White,"Showy, Fragrant",Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,True,False,True
30,Asimina triloba - pawpaw,asimina triloba,pawpaw,Asimina,triloba,ASTR,Yes,Purple,No,Dark Green,Moderate,Porous,Brown,No,No,Mid Spring,Medium,Spring,Summer,Yes,asimina triloba,April to May,Purple,"Fragrant, Insignificant",Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 234, ...",Tree,True,True,False,False,True
31,Betula alleghaniensis - yellow birch,betula alleghaniensis,yellow birch,Betula,alleghaniensis,BEAL2,No,Yellow,No,Green,Dense,Porous,Brown,No,No,Late Spring,Medium,Summer,Summer,Yes,betula alleghaniensis,April to May,"Female catkins green, male catkins mature from...",N/a,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
32,Betula lenta - sweet birch,betula lenta,sweet birch,Betula,lenta,BELE,No,Yellow,No,Green,Moderate,Porous,Brown,No,No,Late Spring,Low,Summer,Fall,No,betula lenta,April to May,Green to pale yellow catkins,Insignificant,"Fragrant, Good Fall",https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
33,Betula nigra - river birch,betula nigra,river birch,Betula,nigra,BENI,No,Brown,No,Green,Moderate,Porous,Brown,No,No,Mid Spring,High,Spring,Spring,No,betula nigra,April to May,Brown (male) green (female),Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",Tree,True,True,True,False,False
34,Betula papyrifera - paper birch,betula papyrifera,paper birch,Betula,papyrifera,BEPA,Yes,Yellow,Yes,Green,Moderate,Porous,Brown,No,No,Mid Spring,High,Summer,Summer,Yes,betula papyrifera,March to April,Yellowish brown (male) and green (female),Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True
35,Betula pendula - european birch,betula pendula,european birch,Betula,pendula,BEPE3,Yes,Brown,Yes,Green,Moderate,Porous,Brown,No,No,Mid Spring,Medium,Summer,Summer,No,betula pendula,March to April,Yellowish brown (male) & green (female),Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True
36,Betula populifolia - gray birch,betula populifolia,gray birch,Betula,populifolia,BEPO,Yes,Brown,No,Green,Moderate,Porous,Brown,No,No,Mid Spring,High,Summer,Fall,No,betula populifolia,April,Yellow-brown (male) and green (female),Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True
37,Catalpa bignonioides - southern catalpa,catalpa bignonioides,southern catalpa,Catalpa,bignonioides,CABI8,No,White,Yes,Green,Dense,Porous,Green,Yes,No,Mid Spring,Medium,Summer,Summer,No,catalpa bignonioides,May to June,White with purple and yellow markings,Showy,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[121, 122, 123, 124, 125, 126, 127, 128, 129, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,False
38,Carpinus caroliniana - american hornbeam,carpinus caroliniana,american hornbeam,Carpinus,caroliniana,CACA18,Yes,Orange,Yes,Green,Dense,Porous,Brown,No,No,Mid Spring,Medium,Summer,Fall,No,carpinus caroliniana,February,"White (female), Green (male)",Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 4...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True
39,Carya cordiformis - bitternut hickory,carya cordiformis,bitternut hickory,Carya,cordiformis,CACO15,Yes,Green,No,Green,Dense,Porous,Brown,Yes,No,Mid Spring,Medium,Summer,Fall,Yes,carya cordiformis,April to May,Green,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
40,Castanea dentata - american chestnut,castanea dentata,american chestnut,Castanea,dentata,CADE12,Yes,White,No,Yellow-Green,Dense,Porous,Brown,Yes,No,Early Summer,Medium,Summer,Fall,Yes,castanea dentata,June,Yellow-white,Insignificant,N/a,https://www.missouribotanicalgarden.org/PlantF...,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
41,Casuarina equisetifolia - australian pine,casuarina equisetifolia,australian pine,Casuarina,equisetifolia,CAEQ,No,Red,No,Green,Dense,Dense,Brown,No,Yes,Mid Spring,High,Summer,Fall,No,casuarina equisetifolia,N/a,N/a,N/a,N/a,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 172, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False,True,False
42,Carya glabra - pignut hickory,carya glabra,pignut hickory,Carya,glabra,CAGL8,Yes,Yellow,No,Green,Dense,Porous,Brown,Yes,No,Mid Spring,Medium,Summer,Fall,Yes,carya glabra,April to May,Yellowish-green,Insignificant,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,False,False,True
43,Carya illinoensis - pecan,carya illinoensis,pecan,Carya,illinoensis,CAIL2,No,Yellow,No,Yellow-Green,Dense,Porous,Brown,Yes,No,Early Spring,High,Summer,Fall,Yes,carya illinoensis,N/a,N/a,N/a,N/a,NaN,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",NO_URL,False,True,False,False,False
44,Carya laciniosa - shellbark hickory,carya laciniosa,shellbark hickory,Carya,laciniosa,CALA21,No,Yellow,No,Green,Dense,Porous,Brown,Yes,No,Mid Spring,Low,Summer,Fall,Yes,carya laciniosa,April to May,Greenish-yellow,Showy,Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True
45,Castanea mollissima - chinese chestnut,castanea mollissima,chinese chestnut,Castanea,mollissima,CAMO83,Yes,Yellow,Yes,Green,Porous,Moderate,Brown,Yes,No,Mid Spring,Medium,Summer,Fall,Yes,castanea mollissima,June,Yellowish-white,"Showy, Fragrant",Good Fall,https://www.missouribotanicalgarden.org/PlantF...,"[152, 153, 154, 155, 156, 157, 158, 159, 160, ...","[152, 153, 154, 155, 156, 157, 158, 159, 160, ...",Tree,True,True,True,False,True

In [31]:
mobot_usda_matched[0:51]

,scientific_name,Bloom Description,Morphology/Physiology | Flower Color
0,abies balsamea,Non-flowering,Yellow
1,abies fraseri,N/a,Purple
3,acer negundo,Greenish-yellow,White
6,acer platanoides,Yellow,Green
7,acer platanoides,Yellow,Green
8,acer pseudoplatanus,Yellow green,Green
9,acer rubrum,"Red, sometimes yellow",Red
10,acer rubrum,"Red, sometimes yellow",Red
11,acer rubrum,"Red, sometimes yellow",Red
12,acer rubrum,"Red, sometimes yellow",Red
13,acer rubrum,"Red, sometimes yellow",Red
14,acer rubrum,"Red, sometimes yellow",Red
15,acer saccharinum,Greenish-yellow,Yellow
16,acer saccharum,Greenish,Green
17,acer saccharum,Greenish,Green
18,acer saccharum,Greenish,Green
19,acer saccharum,Greenish,Green
20,acer saccharum,Greenish,Green
21,acer saccharum,Greenish,Green
23,aesculus glabra,Greenish-yellow,Green
24,aesculus pavia,Bright red,Red
25,ailanthus altissima,Greenish,Green
26,alnus glutinosa,"Reddish-brown (male), purple (female)",Purple
27,albizia julibrissin,Pink,White
28,amelanchier arborea,White,White
29,amelanchier laevis,White,White
30,asimina triloba,Purple,Purple
31,betula alleghaniensis,"Female catkins green, male catkins mature from...",Yellow
32,betula lenta,Green to pale yellow catkins,Yellow
33,betula nigra,Brown (male) green (female),Brown
34,betula papyrifera,Yellowish brown (male) and green (female),Yellow
35,betula pendula,Yellowish brown (male) & green (female),Brown
36,betula populifolia,Yellow-brown (male) and green (female),Brown
37,catalpa bignonioides,White with purple and yellow markings,White
38,carpinus caroliniana,"White (female), Green (male)",Orange
39,carya cordiformis,Green,Green
40,castanea dentata,Yellow-white,White
42,carya glabra,Yellowish-green,Yellow
44,carya laciniosa,Greenish-yellow,Yellow
45,castanea mollissima,Yellowish-white,Yellow
46,carya ovata,Greenish-yellow,Yellow
48,catalpa speciosa,White with purple and yellow interior spotting,White
49,carya tomentosa,Yellowish-green,Yellow
50,cercis canadensis,Pink,Purple
51,cercis canadensis,Pink,Purple
52,cedrus deodara,Non-flowering,Green
53,celtis laevigata,Green,Green
54,celtis occidentalis,Green,Green
55,celtis occidentalis,Green,Green
56,chamaecyparis thyoides,Non-flowering,Green
57,chionanthus virginicus,Creamy white,White