# Missouri Botanical Garden Plant Finder Scraper

Scrapes Bloom Time, Bloom Description, and Flower fields for a list of scientific names.

Flow per name:
1. GET search page → grab ASP.NET viewstate tokens
2. POST search form with `BasicListView` selected and the name in the search box
3. If a result page comes back: scan the result `<a>` tags for a case-insensitive exact match
4. If a detail page comes back directly (single-hit redirect): scrape it
5. Pull the three fields; missing field → `N/a`

In [21]:
import re
import time
from urllib.parse import urljoin

import pandas as pd
import requests
from bs4 import BeautifulSoup
import geopandas as gpd
BASE_URL = "https://www.missouribotanicalgarden.org"
SEARCH_URL = f"{BASE_URL}/plantfinder/plantfindersearch.aspx"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Referer": "https://www.missouribotanicalgarden.org/plantfinder/plantfindersearch.aspx",
    "Upgrade-Insecure-Requests": "1",
}

REQUEST_DELAY = 1.0  # seconds between requests — be polite

## Helpers

In [22]:
def normalize(text: str) -> str:
    """Collapse whitespace and lowercase for matching."""
    return re.sub(r"\s+", " ", text).strip().lower()


def get_form_state(session: requests.Session) -> dict:
    """Fetch the search page and return ASP.NET hidden form fields."""
    resp = session.get(SEARCH_URL, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")
    state = {}
    for field in ("__VIEWSTATE", "__VIEWSTATEGENERATOR", "__EVENTVALIDATION"):
        tag = soup.find("input", {"name": field})
        state[field] = tag["value"] if tag else ""
    return state


def submit_search(session: requests.Session, name: str, state: dict) -> requests.Response:
    """POST the search form with BasicListView selected."""
    form_data = {
        "__EVENTTARGET": "",
        "__EVENTARGUMENT": "",
        **state,
        "ctl00$MainContentPlaceHolder$BasicSearchCtrl$BasicSearchType": "BasicListView",
        "ctl00$MainContentPlaceHolder$BasicSearchCtrl$CommonNameSearch": name,
        "ctl00$MainContentPlaceHolder$BasicSearchCtrl$BasicSearchButton": "Search",
    }
    resp = session.post(SEARCH_URL, data=form_data, headers=HEADERS, timeout=30, allow_redirects=True)
    resp.raise_for_status()
    return resp

In [23]:
def is_detail_page(soup: BeautifulSoup) -> bool:
    """Detail pages have the Common Name row; result lists don't."""
    return soup.find("div", id="MainContentPlaceHolder_CommonNameRow") is not None


def find_exact_match_url(soup: BeautifulSoup, name: str) -> str | None:
    """Scan list-view results for a case-insensitive exact text match.
    Matches against the <a>'s visible text only (excluding the common-name suffix
    that lives outside the anchor)."""
    target = normalize(name)
    # The results container has id containing 'SearchResults_pnlList'. The dnn_ctrXXXX
    # prefix can vary across deploys, so match by suffix.
    container = soup.find("div", id=re.compile(r"SearchResults_pnlList$"))
    if container is None:
        return None
    for link in container.find_all("a", href=True):
        link_text = normalize(link.get_text(" ", strip=True))
        if link_text == target:
            return urljoin(BASE_URL, link["href"])
    return None


def extract_field(soup: BeautifulSoup, row_id: str, label: str) -> str:
    row = soup.find("div", id=row_id)
    if row is None:
        return "N/a"
    text = row.get_text(" ", strip=True)
    # Strip the leading label, e.g. 'Bloom Time:'
    if text.lower().startswith(label.lower()):
        text = text[len(label):]
    return text.strip(" :") or "N/a"


def extract_unlabeled_row(soup: BeautifulSoup, label: str) -> str:
    """Some rows (Flower, Leaf, Attracts, Suggested Use, ...) have no id —
    they're plain div.row elements. Find by leading text label."""
    needle = label.lower() + ":"
    for row in soup.find_all("div", class_="row"):
        text = row.get_text(" ", strip=True)
        if text.lower().startswith(needle):
            return text.split(":", 1)[1].strip() or "N/a"
    return "N/a"


def scrape_detail(soup: BeautifulSoup) -> dict:
    return {
        "Bloom Time": extract_field(soup, "MainContentPlaceHolder_BloomTimeRow", "Bloom Time:"),
        "Bloom Description": extract_field(soup, "MainContentPlaceHolder_ColorTextRow", "Bloom Description:"),
        "Flower": extract_unlabeled_row(soup, "Flower"),
        "Leaf": extract_unlabeled_row(soup, "Leaf"),
    }

In [24]:
def lookup_plant(session: requests.Session, name: str) -> dict:
    """Run the full search → match → scrape pipeline for one name."""
    result = {
        "Scientific Name": name,
        "Bloom Time": "N/a",
        "Bloom Description": "N/a",
        "Flower": "N/a",
        "Leaf": "N/a",
        "Status": "",
        "Detail URL": "",
    }
    try:
        state = get_form_state(session)
        resp = submit_search(session, name, state)
        soup = BeautifulSoup(resp.text, "html.parser")

        # Case 1: search jumped straight to a detail page (single match)
        if is_detail_page(soup):
            result.update(scrape_detail(soup))
            result["Status"] = "matched (single)"
            result["Detail URL"] = resp.url
            return result

        # Case 2: list view — look for exact match
        detail_url = find_exact_match_url(soup, name)
        if detail_url is None:
            result["Status"] = "no exact match"
            return result

        time.sleep(REQUEST_DELAY)
        detail_resp = session.get(detail_url, headers=HEADERS, timeout=30)
        detail_resp.raise_for_status()
        detail_soup = BeautifulSoup(detail_resp.text, "html.parser")
        result.update(scrape_detail(detail_soup))
        result["Status"] = "matched"
        result["Detail URL"] = detail_url
        return result

    except requests.RequestException as e:
        result["Status"] = f"request error: {e}"
        return result
    except Exception as e:
        result["Status"] = f"error: {e}"
        return result

In [25]:
from difflib import SequenceMatcher


def similarity(a: str, b: str) -> float:
    """Ratio in [0, 1]. Empty strings → 0."""
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


def parse_result_row(div) -> dict | None:
    """Pull scientific name (link text), common name (trailing text), and URL
    from a single result row div."""
    link = div.find("a", href=True)
    if link is None:
        return None
    sci_raw = link.get_text(" ", strip=True)
    full = div.get_text(" ", strip=True)
    # Everything after the link text, with the ' - ' separator stripped
    common_raw = full[len(sci_raw):].lstrip(" -\u2013\u2014").strip()
    return {
        "scientific": normalize(sci_raw),
        "common": normalize(common_raw),
        "url": urljoin(BASE_URL, link["href"]),
    }


def find_best_match(soup, scientific_name: str, common_name: str | None) -> tuple[str | None, str]:
    """Return (detail_url, status). Applies single-result rule first, then fuzzy scoring."""
    container = soup.find("div", id=re.compile(r"SearchResults_pnlList$"))
    if container is None:
        return None, "no results container"

    rows = [parse_result_row(d) for d in container.find_all("div", recursive=False)]
    rows = [r for r in rows if r is not None]

    if not rows:
        return None, "no results"

    # Rule 1: single result — just take it
    if len(rows) == 1:
        return rows[0]["url"], "single result"

    # Rule 2: fuzzy score on scientific + common
    q_sci = normalize(scientific_name)
    q_com = normalize(common_name) if common_name else ""

    scored = []
    for r in rows:
        s_sci = similarity(q_sci, r["scientific"])
        s_com = similarity(q_com, r["common"])
        scored.append((s_sci + s_com, s_sci, s_com, r))
    scored.sort(key=lambda x: x[0], reverse=True)
    total, s_sci, s_com, best = scored[0]
    return best["url"], f"fuzzy (sci={s_sci:.2f}, com={s_com:.2f})"

In [26]:
def lookup_plant_fuzzy(session: requests.Session, scientific_name: str, common_name: str | None = None) -> dict:
    """Second-pass lookup: single-result rule first, then fuzzy match using common name."""
    result = {
        "Scientific Name": scientific_name,
        "Bloom Time": "N/a", "Bloom Description": "N/a", "Flower": "N/a", "Leaf": "N/a",
        "Status": "", "Detail URL": "",
    }
    try:
        state = get_form_state(session)
        resp = submit_search(session, scientific_name, state)
        soup = BeautifulSoup(resp.text, "html.parser")

        # Single-result auto-redirect to detail page
        if is_detail_page(soup):
            result.update(scrape_detail(soup))
            result["Status"] = "matched (single redirect)"
            result["Detail URL"] = resp.url
            return result

        detail_url, status = find_best_match(soup, scientific_name, common_name)
        if detail_url is None:
            result["Status"] = status
            return result

        time.sleep(REQUEST_DELAY)
        detail_resp = session.get(detail_url, headers=HEADERS, timeout=30)
        detail_resp.raise_for_status()
        detail_soup = BeautifulSoup(detail_resp.text, "html.parser")
        result.update(scrape_detail(detail_soup))
        result["Status"] = status
        result["Detail URL"] = detail_url
        return result

    except Exception as e:
        result["Status"] = f"error: {e}"
        return result

## Run

Drop your scientific names into `names_to_lookup` (or load from a CSV).

In [37]:
trees = gpd.read_file("../data/processed/philly_trees.geojson")
trees["scientific_name"] = trees["scientific_name"].str.lower()
trees["common_name"] = trees["common_name"].str.lower()

In [45]:
species = trees.drop_duplicates(subset="scientific_name")

names_to_lookup = list(species["scientific_name"])
print(len(names_to_lookup))

# Or, from a file:
# names_to_lookup = pd.read_csv("species_list.csv")["scientific_name"].dropna().tolist()

251

In [11]:
rows = []
with requests.Session() as session:
    for i, name in enumerate(names_to_lookup, 1):
        print(f"[{i}/{len(names_to_lookup)}] {name}")
        row = lookup_plant(session, name)
        print(f"    → {row['Status']}")
        rows.append(row)
        time.sleep(REQUEST_DELAY)

df = pd.DataFrame(rows, columns=[
    "Scientific Name", "Bloom Time", "Bloom Description", "Flower", "Leaf", "Status", "Detail URL"
])
df

[1/251] ginkgo biloba
    → matched
[2/251] acer palmatum
    → matched
[3/251] acer pseudoplatanus
    → matched
[4/251] ilex opaca
    → matched
[5/251] koelreuteria paniculata
    → matched
[6/251] cornus kousa
    → matched
[7/251] amelanchier species
    → no exact match
[8/251] metasequoia glyptostroboides
    → matched
[9/251] acer rubrum
    → matched
[10/251] liriodendron tulipifera
    → matched
[11/251] fraxinus americana
    → matched
[12/251] betula nigra
    → matched
[13/251] taxodium distichum
    → no exact match
[14/251] liquidambar styraciflua
    → matched
[15/251] quercus palustris
    → matched
[16/251] pinus strobus
    → matched
[17/251] prunus sargentii
    → matched
[18/251] gleditsia triacanthos inermis
    → no exact match
[19/251] robinia pseudoacacia
    → matched
[20/251] prunus species
    → no exact match
[21/251] maackia amurensis
    → matched
[22/251] syringa reticulata
    → matched
[23/251] parrotia persica
    → matched
[24/251] styrax japonicus
    → matched
[25/251] cotinus coggygria
    → matched
[26/251] quercus bicolor
    → matched
[27/251] quercus rubra
    → matched
[28/251] ostrya virginiana
    → matched
[29/251] carpinus betulus
    → matched
[30/251] quercus macrocarpa
    → matched
[31/251] quercus laevis
    → no exact match
[32/251] malus species
    → no exact match
[33/251] platanus acerifolia
    → no exact match
[34/251] tilia americana
    → matched
[35/251] cercidiphyllum japonicum
    → matched
[36/251] acer saccharum
    → matched
[37/251] magnolia species
    → no exact match
[38/251] gleditsia triacanthos
    → matched
[39/251] tilia cordata
    → matched
[40/251] aesculus octandra
    → no exact match
[41/251] crataegus species
    → no exact match
[42/251] ulmus americana
    → matched
[43/251] cladrastis kentukea
    → matched
[44/251] ulmus parvifolia
    → matched
[45/251] diospyros virginiana
    → matched
[46/251] nyssa sylvatica
    → matched
[47/251] magnolia virginiana
    → matched
[48/251] pyrus calleryana
    → no exact match
[49/251] zelkova serrata
    → matched
[50/251] quercus alba
    → matched
[51/251] amelanchier laevis
    → matched
[52/251] acer platanoides
    → matched
[53/251] pinus resinosa
    → matched
[54/251] aesculus species
    → no exact match
[55/251] quercus phellos
    → matched
[56/251] prunus serotina
    → matched
[57/251] aesculus carnea
    → no exact match
[58/251] morus alba
    → matched
[59/251] quercus coccinea
    → matched
[60/251] broussonetia papyrifera
    → matched
[61/251] fagus sylvatica
    → matched
[62/251] cornus florida
    → matched
[63/251] cornus mas
    → matched
[64/251] acer freemanii
    → no exact match
[65/251] magnolia stellata
    → matched
[66/251] ulmus species
    → no exact match
[67/251] catalpa speciosa
    → matched
[68/251] magnolia soulangiana
    → no exact match
[69/251] cercis canadensis
    → matched
[70/251] gymnocladus dioicus
    → matched
[71/251] quercus imbricaria
    → matched
[72/251] juniperus virginiana
    → matched
[73/251] chionanthus virginicus
    → matched
[74/251] magnolia grandiflora
    → matched
[75/251] cedrella sinensis
    → no exact match
[76/251] cornus species
    → no exact match
[77/251] prunus serrulata
    → matched
[78/251] fagus grandifolia
    → matched
[79/251] quercus velutina
    → matched
[80/251] halesia carolina
    → matched
[81/251] quercus acutissima
    → matched
[82/251] lagerstroemia indica
    → matched
[83/251] acer saccharinum
    → matched
[84/251] celtis occidentalis
    → matched
[85/251] acer nigrum
    → no exact match
[86/251] prunus persica
    → no exact match
[87/251] magnolia acuminata
    → matched
[88/251] carpinus caroliniana
    → matched
[89/251] crataegus phaenopyrum
    → matched
[90/251] prunus subhirtella
    → matched
[91/251] hamamelis virginiana
    → matched
[92/251] shrub shrub
    → no exact match
[93/251] ailanthus altissima
    → matched
[94/251] quercus robur
    → matched
[95/251] acer campestre
    → matched
[96/251] pinus rigida
    → no exact match
[97/251] tsuga canadensis
    → matched
[98/251] sophora japonica
    → no exact match
[99/251] juglans nigra
    → matched
[100/251] fraxinus pennsylvanica
    → matched
[101/251] tetradium daniellii
    → matched
[102/251] chionanthus retusus
    → matched
[103/251] taxus species
    → no exact match
[104/251] chamaecyparis thyoides
    → matched
[105/251] salix species
    → no exact match
[106/251] larix decidua
    → matched
[107/251] cryptomeria japonica
    → matched
[108/251] picea glauca
    → matched
[109/251] picea pungens
    → matched
[110/251] populus tremuloides
    → matched
[111/251] pinus species
    → no exact match
[112/251] castanea mollissima
    → matched
[113/251] ulmus pumila
    → matched
[114/251] sassafras albidum
    → matched
[115/251] betula populifolia
    → matched
[116/251] picea species
    → no exact match
[117/251] pseudotsuga menziesii
    → matched
[118/251] eucommia ulmoides
    → matched
[119/251] carya ovata
    → matched
[120/251] aesculus hippocastanum
    → matched
[121/251] carya species
    → no exact match
[122/251] paulownia tomentosa
    → matched
[123/251] acer negundo
    → matched
[124/251] crataegus crus-galli
    → matched
[125/251] salix nigra
    → matched
[126/251] pinus sylvestris
    → matched
[127/251] carya tomentosa
    → matched
[128/251] acer ginnala
    → no exact match
[129/251] pinus nigra
    → matched
[130/251] morus rubra
    → matched
[131/251] tilia tomentosa
    → matched
[132/251] acer griseum
    → matched
[133/251] acer species
    → no exact match
[134/251] prunus cerasifera
    → matched
[135/251] acer buergeranum
    → no exact match
[136/251] malus pumila
    → no exact match
[137/251] quercus prinus
    → no exact match
[138/251] quercus species
    → no exact match
[139/251] abies species
    → no exact match
[140/251] cedrus atlantica
    → matched
[141/251] asimina triloba
    → matched
[142/251] carya cordiformis
    → matched
[143/251] maclura pomifera
    → matched
[144/251] ulmus thomasii
    → no exact match
[145/251] thuja occidentalis
    → matched
[146/251] platanus occidentalis
    → matched
[147/251] prunus avium
    → matched
[148/251] carya glabra
    → matched
[149/251] salix babylonica
    → matched
[150/251] quercus muehlenbergii
    → matched
[151/251] betula papyrifera
    → matched
[152/251] rhus glabra
    → matched
[153/251] populus deltoides
    → matched
[154/251] phellodendron amurense
    → matched
[155/251] quercus warei
    → no exact match
[156/251] crataegus monogyna
    → no exact match
[157/251] crataegus marshallii
    → no exact match
[158/251] ulmus rubra
    → matched
[159/251] betula lenta
    → matched
[160/251] quercus falcata
    → matched
[161/251] quercus stellata
    → matched
[162/251] pinus taeda
    → matched
[163/251] fraxinus species
    → no exact match
[164/251] tilia species
    → no exact match
[165/251] quercus ellipsoidalis
    → matched
[166/251] albizia julibrissin
    → matched
[167/251] casuarina equisetifolia
    → no exact match
[168/251] salix matsudana
    → no exact match
[169/251] pyrus communis
    → matched
[170/251] aesculus glabra
    → matched
[171/251] abies fraseri
    → matched
[172/251] cedrus deodara
    → matched
[173/251] prunus pennsylvanica
    → no exact match
[174/251] prunus padus
    → matched
[175/251] prunus americana
    → matched
[176/251] ilex species
    → no exact match
[177/251] ficus carica
    → matched
[178/251] castanea dentata
    → matched
[179/251] juglans regia
    → matched
[180/251] prunus maackii
    → matched
[181/251] rhus typhina
    → matched
[182/251] carya laciniosa
    → matched
[183/251] oxydendrum arboreum
    → matched
[184/251] stewartia koreana
    → no exact match
[185/251] poplar species
    → no exact match
[186/251] fagus species
    → no exact match
[187/251] prunus triloba
    → matched
[188/251] prunus armeniaca
    → no exact match
[189/251] corylus colurna
    → matched
[190/251] castanea species
    → no exact match
[191/251] hibiscus syriacus
    → matched
[192/251] stewartia species
    → no exact match
[193/251] prunus yedoensis
    → no exact match
[194/251] magnolia tripetala
    → matched
[195/251] prunus virginiana
    → matched
[196/251] abies balsamea
    → matched
[197/251] quercus shumardii
    → matched
[198/251] euonymus atropurpureus
    → matched
[199/251] viburnum trilobum
    → no exact match
[200/251] populus trichocarpa
    → no exact match
[201/251] cupressus species
    → no exact match
[202/251] pinus virginiana
    → no exact match
[203/251] alnus glutinosa
    → matched
[204/251] franklinia alatamaha
    → matched
[205/251] acer pensyvanicum
    → no exact match
[206/251] juglans cinerea
    → matched
[207/251] betula alleghaniensis
    → matched
[208/251] elaeagnus umbellata
    → matched
[209/251] thuja orientalis
    → no exact match
[210/251] fraxinus nigra
    → no exact match
[211/251] kalopanax semtemlobus
    → no exact match
[212/251] castanea pumila
    → no exact match
[213/251] acer tataricum
    → matched
[214/251] carya illinoensis
    → no exact match
[215/251] larix laricina
    → matched
[216/251] quercus michauxii
    → matched
[217/251] catalpa bignonioides
    → matched
[218/251] picea mariana
    → no exact match
[219/251] prunus incamp
    → no exact match
[220/251] betula species
    → no exact match
[221/251] populus grandidentata
    → no exact match
[222/251] crataegus viridis
    → matched
[223/251] quercus lyrata
    → matched
[224/251] syringia reticulata
    → no exact match
[225/251] amelanchier grandiflora
    → no exact match
[226/251] populus alba
    → matched
[227/251] prunus caroliniana
    → matched
[228/251] quercus marilandica
    → matched
[229/251] acer truncatum
    → matched
[230/251] cornus rutban
    → no exact match
[231/251] ulmus procera
    → no exact match
[232/251] alnus species
    → no exact match
[233/251] ulmus frontier
    → no exact match
[234/251] betula pendula
    → matched
[235/251] quercus nigra
    → matched
[236/251] laburnum watereri
    → no exact match
[237/251] sorbus species
    → no exact match
[238/251] ulmus emerald sunshine
    → no exact match
[239/251] acer triflorum
    → matched
[240/251] celtis laevigata
    → matched
[241/251] stewartia monadelpha
    → no exact match
[242/251] quercus laurifolia
    → matched
[243/251] amelanchier arborea
    → matched
[244/251] aesculus pavia
    → matched
[245/251] rosa species
    → no exact match
[246/251] prunus angustifolia
    → matched
[247/251] sorbus aucuparia
    → matched
[248/251] sorbus americana
    → matched
[249/251] acer henryii
    → no exact match
[250/251] ulmus alata
    → matched
[251/251] prunus amanogawa
    → no exact match

,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL
0,ginkgo biloba,April,Green,Insignificant,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
1,acer palmatum,April,Reddish-purple,Insignificant,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
2,acer pseudoplatanus,May,Yellow green,Insignificant,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
3,ilex opaca,May,Creamy white,Insignificant,Evergreen,matched,https://www.missouribotanicalgarden.org/PlantF...
4,koelreuteria paniculata,June to July,Yellow,Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
...,...,...,...,...,...,...,...
246,sorbus aucuparia,May,White,Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
247,sorbus americana,May,White,Showy,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
248,acer henryii,N/a,N/a,N/a,N/a,no exact match,
249,ulmus alata,March to April,Reddish green,Insignificant,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
250,prunus amanogawa,N/a,N/a,N/a,N/a,no exact match,

In [30]:
#df.to_csv("mobot_plant_data.csv", index=False)
print(f"Saved {len(df)} rows → mobot_plant_data.csv")

Saved 251 rows → mobot_plant_data.csv

## Second pass: single-result + fuzzy fallback

After the first pass, gather rows where `Status == 'no exact match'`. Build a `{scientific_name: common_name}` dict for those and run them through `lookup_plant_fuzzy`. The rules:

1. If the search returns a single result, take it (no name comparison needed — common case is the base species existing only as a named cultivar, e.g. `pinus virginiana` → `Pinus virginiana 'Wate's Golden'`).
2. If multiple results, score each result against your scientific name *and* the common name you provide, pick the highest combined similarity. The common name is what discriminates between cultivars.

Uses `difflib.SequenceMatcher` from stdlib — no extra dependency.

### Run the fallback on failed names

After your first-pass `df` is built, identify the failures, fill in the `common_names` dict, and run the fallback. Results get merged back into `df`.

In [46]:
misses = df.loc[df["Status"] != "matched"]
specific_misses = misses.loc[~misses["Scientific Name"].str.contains("species")]
specific_misses

,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL
12,taxodium distichum,N/a,N/a,N/a,N/a,no exact match,
17,gleditsia triacanthos inermis,N/a,N/a,N/a,N/a,no exact match,
30,quercus laevis,N/a,N/a,N/a,N/a,no exact match,
32,platanus acerifolia,N/a,N/a,N/a,N/a,no exact match,
39,aesculus octandra,N/a,N/a,N/a,N/a,no exact match,
47,pyrus calleryana,N/a,N/a,N/a,N/a,no exact match,
56,aesculus carnea,N/a,N/a,N/a,N/a,no exact match,
63,acer freemanii,N/a,N/a,N/a,N/a,no exact match,
67,magnolia soulangiana,N/a,N/a,N/a,N/a,no exact match,
74,cedrella sinensis,N/a,N/a,N/a,N/a,no exact match,
84,acer nigrum,N/a,N/a,N/a,N/a,no exact match,
85,prunus persica,N/a,N/a,N/a,N/a,no exact match,
91,shrub shrub,N/a,N/a,N/a,N/a,no exact match,
95,pinus rigida,N/a,N/a,N/a,N/a,no exact match,
97,sophora japonica,N/a,N/a,N/a,N/a,no exact match,
127,acer ginnala,N/a,N/a,N/a,N/a,no exact match,
134,acer buergeranum,N/a,N/a,N/a,N/a,no exact match,
135,malus pumila,N/a,N/a,N/a,N/a,no exact match,
136,quercus prinus,N/a,N/a,N/a,N/a,no exact match,
143,ulmus thomasii,N/a,N/a,N/a,N/a,no exact match,
154,quercus warei,N/a,N/a,N/a,N/a,no exact match,
155,crataegus monogyna,N/a,N/a,N/a,N/a,no exact match,
156,crataegus marshallii,N/a,N/a,N/a,N/a,no exact match,
166,casuarina equisetifolia,N/a,N/a,N/a,N/a,no exact match,
167,salix matsudana,N/a,N/a,N/a,N/a,no exact match,
172,prunus pennsylvanica,N/a,N/a,N/a,N/a,no exact match,
183,stewartia koreana,N/a,N/a,N/a,N/a,no exact match,
187,prunus armeniaca,N/a,N/a,N/a,N/a,no exact match,
192,prunus yedoensis,N/a,N/a,N/a,N/a,no exact match,
198,viburnum trilobum,N/a,N/a,N/a,N/a,no exact match,
199,populus trichocarpa,N/a,N/a,N/a,N/a,no exact match,
201,pinus virginiana,N/a,N/a,N/a,N/a,no exact match,
204,acer pensyvanicum,N/a,N/a,N/a,N/a,no exact match,
208,thuja orientalis,N/a,N/a,N/a,N/a,no exact match,
209,fraxinus nigra,N/a,N/a,N/a,N/a,no exact match,
210,kalopanax semtemlobus,N/a,N/a,N/a,N/a,no exact match,
211,castanea pumila,N/a,N/a,N/a,N/a,no exact match,
213,carya illinoensis,N/a,N/a,N/a,N/a,no exact match,
217,picea mariana,N/a,N/a,N/a,N/a,no exact match,
218,prunus incamp,N/a,N/a,N/a,N/a,no exact match,
220,populus grandidentata,N/a,N/a,N/a,N/a,no exact match,
223,syringia reticulata,N/a,N/a,N/a,N/a,no exact match,
224,amelanchier grandiflora,N/a,N/a,N/a,N/a,no exact match,
229,cornus rutban,N/a,N/a,N/a,N/a,no exact match,
230,ulmus procera,N/a,N/a,N/a,N/a,no exact match,
232,ulmus frontier,N/a,N/a,N/a,N/a,no exact match,
235,laburnum watereri,N/a,N/a,N/a,N/a,no exact match,
237,ulmus emerald sunshine,N/a,N/a,N/a,N/a,no exact match,
240,stewartia monadelpha,N/a,N/a,N/a,N/a,no exact match,
248,acer henryii,N/a,N/a,N/a,N/a,no exact match,
250,prunus amanogawa,N/a,N/a,N/a,N/a,no exact match,

In [48]:
# create list of missed scientific names
missed_s_names = list(specific_misses["Scientific Name"])
missed_s_names
# take slice of tree databse with the only species info for missed ones
missed_species = species[species["scientific_name"].isin(missed_s_names)]
missed_species
name_dict = dict(zip(missed_species["scientific_name"], missed_species["common_name"]))

In [49]:
# 2. Fill in the common name for each failed scientific name.
#    Common name is only needed when there are multiple results — for single-result
#    species you can leave the value as None or empty.
common_names = name_dict

# 3. Run the fallback
fallback_rows = []
with requests.Session() as session:
    for i, (sci_name, com_name) in enumerate(common_names.items(), 1):
        print(f"[{i}/{len(common_names)}] {sci_name}  (common: {com_name!r})")
        row = lookup_plant_fuzzy(session, sci_name, com_name)
        print(f"    → {row['Status']}")
        fallback_rows.append(row)
        time.sleep(REQUEST_DELAY)

fallback_df = pd.DataFrame(fallback_rows, columns=df.columns)
fallback_df

[1/51] taxodium distichum  (common: 'baldcypress')
    → fuzzy (sci=0.78, com=0.96)
[2/51] gleditsia triacanthos inermis  (common: 'thornless honeylocust')
    → no results container
[3/51] quercus laevis  (common: 'turkey oak')
    → no results container
[4/51] platanus acerifolia  (common: 'london planetree')
    → no results container
[5/51] aesculus octandra  (common: 'yellow buckeye')
    → no results container
[6/51] pyrus calleryana  (common: 'callery pear')
    → fuzzy (sci=0.76, com=1.00)
[7/51] aesculus carnea  (common: 'red horsechestnut')
    → no results container
[8/51] acer freemanii  (common: 'armstrong maple')
    → no results container
[9/51] magnolia soulangiana  (common: 'saucer magnolia')
    → no results container
[10/51] cedrella sinensis  (common: 'chinese toon')
    → no results container
[11/51] acer nigrum  (common: 'black maple')
    → no results container
[12/51] prunus persica  (common: 'peach')
    → fuzzy (sci=0.74, com=1.00)
[13/51] shrub shrub  (common: 'shrub')
    → no results container
[14/51] pinus rigida  (common: 'pitch pine')
    → no results container
[15/51] sophora japonica  (common: 'japanese pagoda tree')
    → fuzzy (sci=0.78, com=1.00)
[16/51] acer ginnala  (common: 'amur maple')
    → no results container
[17/51] acer buergeranum  (common: 'trident maple')
    → no results container
[18/51] malus pumila  (common: 'apple')
    → fuzzy (sci=0.73, com=1.00)
[19/51] quercus prinus  (common: 'chestnut oak')
    → no results container
[20/51] ulmus thomasii  (common: 'rock elm')
    → no results container
[21/51] quercus warei  (common: 'regal prince oak')
    → no results container
[22/51] crataegus monogyna  (common: 'english hawthorn')
    → no results container
[23/51] crataegus marshallii  (common: 'parsley hawthorn')
    → no results container
[24/51] casuarina equisetifolia  (common: 'australian pine')
    → no results container
[25/51] salix matsudana  (common: 'corkscrew willow')
    → no results container
[26/51] prunus pennsylvanica  (common: 'pin cherry')
    → no results container
[27/51] stewartia koreana  (common: 'korean stewartia')
    → no results container
[28/51] prunus armeniaca  (common: 'apricot')
    → fuzzy (sci=0.63, com=1.00)
[29/51] prunus yedoensis  (common: 'yoshino cherry')
    → no results container
[30/51] viburnum trilobum  (common: 'american cranberry bush')
    → no results container
[31/51] populus trichocarpa  (common: 'black cottonwood')
    → no results container
[32/51] pinus virginiana  (common: 'virginia pine')
    → single result
[33/51] acer pensyvanicum  (common: 'striped maple')
    → no results container
[34/51] thuja orientalis  (common: 'oriental arborvitae')
    → no results container
[35/51] fraxinus nigra  (common: 'black ash')
    → no results container
[36/51] kalopanax semtemlobus  (common: 'tree aralia')
    → no results container
[37/51] castanea pumila  (common: 'allegheny chinkapin')
    → no results container
[38/51] carya illinoensis  (common: 'pecan')
    → no results container
[39/51] picea mariana  (common: 'black spruce')
    → single result
[40/51] prunus incamp  (common: 'okame cherry')
    → no results container
[41/51] populus grandidentata  (common: 'bigtooth aspen')
    → no results container
[42/51] syringia reticulata  (common: 'ivory silk japanese tree lilac')
    → no results container
[43/51] amelanchier grandiflora  (common: 'apple serviceberry')
    → no results container
[44/51] cornus rutban  (common: 'aurora dogwood')
    → no results container
[45/51] ulmus procera  (common: 'english elm')
    → no results container
[46/51] ulmus frontier  (common: 'frontier elm')
    → no results container
[47/51] laburnum watereri  (common: 'golden chain tree')
    → no results container
[48/51] ulmus emerald sunshine  (common: 'emerald sunshine elm')
    → no results container
[49/51] stewartia monadelpha  (common: 'tall stewartia')
    → no results container
[50/51] acer henryii  (common: 'henrys maple')
    → no results container
[51/51] prunus amanogawa  (common: 'oriental cherry')
    → no results container

,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL
0,taxodium distichum,Non-flowering,Non-flowering,N/a,Good Fall,"fuzzy (sci=0.78, com=0.96)",https://www.missouribotanicalgarden.org/PlantF...
1,gleditsia triacanthos inermis,N/a,N/a,N/a,N/a,no results container,
2,quercus laevis,N/a,N/a,N/a,N/a,no results container,
3,platanus acerifolia,N/a,N/a,N/a,N/a,no results container,
4,aesculus octandra,N/a,N/a,N/a,N/a,no results container,
5,pyrus calleryana,April,White,Showy,Good Fall,"fuzzy (sci=0.76, com=1.00)",https://www.missouribotanicalgarden.org/PlantF...
6,aesculus carnea,N/a,N/a,N/a,N/a,no results container,
7,acer freemanii,N/a,N/a,N/a,N/a,no results container,
8,magnolia soulangiana,N/a,N/a,N/a,N/a,no results container,
9,cedrella sinensis,N/a,N/a,N/a,N/a,no results container,
10,acer nigrum,N/a,N/a,N/a,N/a,no results container,
11,prunus persica,March to April,Pink,"Showy, Fragrant",N/a,"fuzzy (sci=0.74, com=1.00)",https://www.missouribotanicalgarden.org/PlantF...
12,shrub shrub,N/a,N/a,N/a,N/a,no results container,
13,pinus rigida,N/a,N/a,N/a,N/a,no results container,
14,sophora japonica,July to August,Creamy white,Showy,N/a,"fuzzy (sci=0.78, com=1.00)",https://www.missouribotanicalgarden.org/PlantF...
15,acer ginnala,N/a,N/a,N/a,N/a,no results container,
16,acer buergeranum,N/a,N/a,N/a,N/a,no results container,
17,malus pumila,April,White,Showy,N/a,"fuzzy (sci=0.73, com=1.00)",https://www.missouribotanicalgarden.org/PlantF...
18,quercus prinus,N/a,N/a,N/a,N/a,no results container,
19,ulmus thomasii,N/a,N/a,N/a,N/a,no results container,
20,quercus warei,N/a,N/a,N/a,N/a,no results container,
21,crataegus monogyna,N/a,N/a,N/a,N/a,no results container,
22,crataegus marshallii,N/a,N/a,N/a,N/a,no results container,
23,casuarina equisetifolia,N/a,N/a,N/a,N/a,no results container,
24,salix matsudana,N/a,N/a,N/a,N/a,no results container,
25,prunus pennsylvanica,N/a,N/a,N/a,N/a,no results container,
26,stewartia koreana,N/a,N/a,N/a,N/a,no results container,
27,prunus armeniaca,April,White,"Showy, Fragrant",N/a,"fuzzy (sci=0.63, com=1.00)",https://www.missouribotanicalgarden.org/PlantF...
28,prunus yedoensis,N/a,N/a,N/a,N/a,no results container,
29,viburnum trilobum,N/a,N/a,N/a,N/a,no results container,
30,populus trichocarpa,N/a,N/a,N/a,N/a,no results container,
31,pinus virginiana,Non-flowering,Non-flowering,N/a,"Colorful, Evergreen",single result,https://www.missouribotanicalgarden.org/PlantF...
32,acer pensyvanicum,N/a,N/a,N/a,N/a,no results container,
33,thuja orientalis,N/a,N/a,N/a,N/a,no results container,
34,fraxinus nigra,N/a,N/a,N/a,N/a,no results container,
35,kalopanax semtemlobus,N/a,N/a,N/a,N/a,no results container,
36,castanea pumila,N/a,N/a,N/a,N/a,no results container,
37,carya illinoensis,N/a,N/a,N/a,N/a,no results container,
38,picea mariana,Non-flowering,Non-flowering,N/a,"Colorful, Evergreen",single result,https://www.missouribotanicalgarden.org/PlantF...
39,prunus incamp,N/a,N/a,N/a,N/a,no results container,
40,populus grandidentata,N/a,N/a,N/a,N/a,no results container,
41,syringia reticulata,N/a,N/a,N/a,N/a,no results container,
42,amelanchier grandiflora,N/a,N/a,N/a,N/a,no results container,
43,cornus rutban,N/a,N/a,N/a,N/a,no results container,
44,ulmus procera,N/a,N/a,N/a,N/a,no results container,
45,ulmus frontier,N/a,N/a,N/a,N/a,no results container,
46,laburnum watereri,N/a,N/a,N/a,N/a,no results container,
47,ulmus emerald sunshine,N/a,N/a,N/a,N/a,no results container,
48,stewartia monadelpha,N/a,N/a,N/a,N/a,no results container,
49,acer henryii,N/a,N/a,N/a,N/a,no results container,
50,prunus amanogawa,N/a,N/a,N/a,N/a,no results container,

In [50]:
# 4. Merge fallback results back into the main df, overwriting the failed rows
df = df.set_index("Scientific Name")
fb = fallback_df.set_index("Scientific Name")
df.update(fb)  # overwrites only matching index values
df = df.reset_index()
df

,Scientific Name,Bloom Time,Bloom Description,Flower,Leaf,Status,Detail URL
0,ginkgo biloba,April,Green,Insignificant,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
1,acer palmatum,April,Reddish-purple,Insignificant,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
2,acer pseudoplatanus,May,Yellow green,Insignificant,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
3,ilex opaca,May,Creamy white,Insignificant,Evergreen,matched,https://www.missouribotanicalgarden.org/PlantF...
4,koelreuteria paniculata,June to July,Yellow,Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
...,...,...,...,...,...,...,...
246,sorbus aucuparia,May,White,Showy,Good Fall,matched,https://www.missouribotanicalgarden.org/PlantF...
247,sorbus americana,May,White,Showy,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
248,acer henryii,N/a,N/a,N/a,N/a,no results container,
249,ulmus alata,March to April,Reddish green,Insignificant,N/a,matched,https://www.missouribotanicalgarden.org/PlantF...
250,prunus amanogawa,N/a,N/a,N/a,N/a,no results container,

In [53]:
df.to_csv("mobot_plant_data.csv", index=False)
print(f"Saved final {len(df)} rows → mobot_plant_data.csv")

Saved final 251 rows → mobot_plant_data.csv

### Debugging tips

- If everything comes back `no exact match`, inspect a response: `print(BeautifulSoup(resp.text, 'html.parser').find('div', id=re.compile(r'SearchResults_pnlList$')))` to see what the list actually looks like. Cultivar names with curly vs straight quotes (`'` vs `'`) trip exact match — normalize your input list.
- If you get blocked / 403s, raise `REQUEST_DELAY` to 2–3 seconds.
- The search box is labeled `CommonNameSearch` in the HTML, but it accepts scientific names too (it's a unified search). No changes needed.